### PR TITLE
Remove generated Boilerplate from scoverage

### PR DESCRIPTION
**Pull request by InTheNow**
Removes the generated code from the code coverage tests.

### CODE REVIEW

**Comment by non** [comment]
:+1:

**Comment by travisbrown** [comment]
What's the argument for treating this code differently? I'm mostly just curious—I don't have a strong opinion either way.

**Comment by InTheNow** [comment]
I suggested this on gitter. I guess the point is that these two files account for a good 8% of checks overall and hence are skewing the overall substantially - and perhaps unreasonably. 

My main reason though, is that the as the files are generated, the source is not in github so are not accessible via the web gui. So the main argument is a pragmatic one, as the test tools do not play nicely here.

**Comment by ceedubs** [comment]
> the test tools do not play nicely here

@InTheNow could you please explain what you mean by that?

My gut reaction is that we are just as likely (if not more-so) to make a mistake in meta-programming than we are in programming, so it's probably right to point out that we don't have coverage on those.

**Comment by InTheNow** [comment]
Have a look at https://codecov.io/github/non/cats/core/target/scala-2.11/src_managed/ and click around on some files.

FTR : like @travisbrown I'm not bothered what you guys decide on, just pointing out the issue. Also, just because test coverage is by default disabled, does not mean that test can be generated and locally tested for coverage

**Comment by travisbrown** [comment]
The local reports do show generated code (IIRC Coveralls does as well, but I might be wrong about that).

It's not ideal that there are 404s in the web interface, but I'm leaning more strongly toward keeping the coverage reporting in place for boilerplate to keep us accountable there.

**Comment by dwijnand** [comment]
(Peanut gallery) I coverage for generated code shouldn't be ignored.

**Comment by InTheNow** [comment]
Perhaps I should rename this PR to "Remove generated Boilerplate _errors_ from scoverage by adding generated tests" and add the appropriate tests? :smile:

**Comment by ceedubs** [comment]
@InTheNow I'm ambivalent about whether we change this issue or create a new one, but I think that would be great if you are willing to add the appropriate tests!

**Comment by InTheNow** [comment]
Replaced by #383

**Pull request closed without merging**
