### PR TITLE
New website

### PR DESCRIPTION
**Pull request by stew**
This is a major restructuring of the website, since the previous incarnation wasn't going to account for the large amount of content I think I'd like to work on pumping into the website.

now the navigation within the typeclass / data type pages is auto-generated from the tut files thanks to @tpolecat!

This thing is buggy, there is certainly room for improvement.

There are certainly a lot of holes in the documentation, but hopefully with all the structure I've put into place, soliciting these contributions will be much easier.

I'm perfectly happy to accept comments on style, I have none, I'm practically amazed I was able to come up with something that doesn't look like complete garbage. Or maybe it does. whatever, please iterate away.

### CODE REVIEW

**Comment by stew** [comment]
Oh, you can see what this would look like here:

http://stew.github.io/cats/

and a good example typeclass page is:

http://stew.github.io/cats//tut/functor.html

**Comment by stew** [comment]
which reminds me that I should throw in a commit to change the ghpage push target to non's repo

**Comment by ceedubs** [comment]
Let a backend guy do your website and you end up with a single character per line in the mobile version :P

This looks great on a normal screen though! It's very snappy too. Thanks for all of the work you've put into this, @stew. I really wish I had this sort of documentation for many other libraries I've used in the past.

I say we get this out there and if someone wants to come along and do a snazzy mobile-compatible version at some point they can. :+1:

**Comment by non** [comment]
Looks great :+1:

**Pull request merged**
