### PR TITLE
Change cats version to 0.3.0 in README.md

### PR DESCRIPTION
**Pull request by matsluni**
Hi,

this is just a version bump in the README.md.

Matthias

### CODE REVIEW

**Comment by non** [comment]
Thanks Matthias!

I was going to wait to bump the version in the README until we put together the release notes and made an announcement. I'll let the PR hang out until then.

**Comment by matsluni** [comment]
Hi Erik,

ok. I was just going to look into cats and found 0.3.0 in the repos and a 0.2.0 version in the README, so I created the PR.

Matthias

**Comment by adelbertc** [comment]
Will also need a change here https://github.com/non/cats/blob/master/docs/src/site/index.md

**Comment by matsluni** [comment]
I also changed the version in index.md.

**Comment by ceedubs** [comment]
:+1:

**Comment by adelbertc** [comment]
:+1:

**Pull request merged**
