### PR TITLE
Free doc: wrap compilePure in tut sheds

### PR DESCRIPTION
**Pull request by fthomas**
This renames `runPure` to `compilePure` which it is called later in the file and wraps the definition with tut sheds. Unfortunately `compilePure(program)` returns an empty `Map` instead of `Map(wild-cats -> 14)`. @mandubian pleas help :-)

### CODE REVIEW

**Comment by mandubian** [comment]
Actually my code was false :)
The last step of the `program` is a `Delete` so it deletes from the map...
Please change the program by changing the name of the key in `Delete` and adding another `Put` step before deleting this key.
Thanks

**Comment by fthomas** [comment]
Ok, done! I've also removed the output of `program.foldMap(impureCompiler)` because tut already outputs this for us and it would therefore appear twice (you can see that here: http://non.github.io/cats//tut/freemonad.html).

I think this is good to merge now (if Travis agrees).

**Comment by mandubian** [comment]
Great, thanks for seeing this ;)
Le 28 avr. 2015 7:06 PM, "Frank S. Thomas" <notifications@github.com> a
écrit :

**Comment by non** [comment]
:+1:  from me. Thanks to both of you for working on this!

**Comment by fthomas** [comment]
Since this is documentation only, I'm merging with only one sign-off.

Thanks again @mandubian for your help!

**Pull request merged**
