### PR TITLE
Remove imports now that we have package-level aliases

### PR DESCRIPTION
**Pull request by travisbrown**
These are causing the build to fail both locally for me and [on Travis](https://travis-ci.org/non/cats/builds/49631620).

### CODE REVIEW

**Comment by travisbrown** [comment]
Oh, new commits just showed up—rebasing this now.

**Comment by travisbrown** [comment]
We can't import `algebra.Monoid` in `Foldable` because of the type alias hiding, but we need the `Monoid` companion object there, not just the type. I've just used the fully-qualified name for the companion object, but that's probably not the best long-term solution (maybe a `val Monoid` in the package object?). My vote is that we can decide on that later and just fix the build for now.

**Comment by non** [comment]
Yes, in another PR I added aliases for the companions.

So once that lands we can change this (or vice versa). Sorry for the incomplete strategy.

**Comment by non** [comment]
I agree, :+1: on this for now.

**Comment by stew** [comment]
yeah, this works for me now :+1:

**Pull request merged**
