### PR TITLE
my man @non likes his fonts like he likes his music, bigger and darker

### PR DESCRIPTION
**Pull request by stew**

### CODE REVIEW

**Comment by tpolecat** [comment]
:metal:

**Comment by stew** [comment]
:metal:

**Comment by stew** [comment]
You ask yourself how much more black that font could be, and the answer is none.

None more black

**Comment by julien-truffaut** [comment]
:+1:

**Comment by milessabin** [comment]
'It's the wild colour scheme that freaks me out,' said Zaphod, whose love affair with the ship had lasted almost three minutes into the flight. 'Every time you try and operate these weird black controls that are labeled in black on a black background, a little black light lights up in black to let you know you've done it.'

**Comment by ceedubs** [comment]
:metal:

**Pull request merged**
