### PR TITLE
Add Kleisli local

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by rossabaker** [comment]
Would "contramap" be a more intuitive name?

**Comment by adelbertc** [comment]
Hm `contramap` in `Contravariant` tends to be for the free type parameter.. maybe `widen`? `expand`?

**Comment by non** [comment]
I'm fine with `local` for now. :+1: 

I agree that `contramap` probably isn't quite right.

**Comment by stew** [comment]
:+1:

**Pull request merged**
