### PR TITLE
add combineAll alias for Foldable's fold

### LINKED ISSUE #482: Foldable fold name clash with TraversableOnce fold
It might be nice to have `Foldable`'s `fold` available in postfix style on `TraversableOnce` instances. @ceedubs suggested an alias in a [gitter discussion](https://gitter.im/non/cats?at=55dd09cf004c3e375ad0be7d).

e.g.
```scala
scala> def i[T : Monoid](v: List[T]) = Foldable[List].fold(v)
i: [T](v: List[T])(implicit evidence$1: cats.Monoid[T])T

scala> def j[T : Monoid](v: List[T]) = v.fold
<console>:16: error: missing arguments for method fold in trait TraversableOnce;
follow this method with `_' if you want to treat it as a partially applied function
       def j[T : Monoid](v: List[T]) = v.fold
                                         ^
```

### PR DESCRIPTION
**Pull request by drostron**
resolves #482

### CODE REVIEW

**Comment by adelbertc** [comment]
Hm are all our `Foldable` syntaxes available by just putting it on `Foldable`? I did not know that.

**Comment by drostron** [comment]
It's available due to [`FoldableSyntax`](https://github.com/non/cats/blob/08ae0deeb8ee5a1f0e338e5f48286f30dbf6294a/core/src/main/scala/cats/syntax/foldable.scala#L12) extending the simulacrum generated `Foldable.ToFoldableOps`.

**Comment by adelbertc** [comment]
Ah right - awesome :-) :+1:

**Comment by ceedubs** [comment]
:+1: thanks!

**Pull request merged**
