### PR TITLE
Make type classes and stuff Serializable, fixes #260

### LINKED ISSUE #260: Serializable type classes
A few folks may be using `cats` in conjunction with Spark which wants `Serializable` things. Related: https://github.com/non/algebra/issues/13

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by non** [comment]
:+1: 

You should also consider adding a serializable test like we have in algebra, e.g.

https://github.com/non/algebra/blob/master/laws/src/main/scala/algebra/laws/Rules.scala#L12

**Comment by adelbertc** [comment]
Ooo good idea, will do that tonight.

**Comment by adelbertc** [comment]
Everything passes except `scala.concurrent.Future` tests:

```
[info] - Future[Int].monad.can serialize and deserialize *** FAILED ***
[info]   GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
[info]    (Discipline.scala:14)
[info]     Falsified after 0 successful property evaluations.
[info]     Location: (Discipline.scala:14)
[info]     Occurred when passed generated values (
[info]       arg0 = scala.concurrent.impl.Promise$KeptPromise@11dd7035
[info]     )
```

Not sure what to do, I think `Future` is just inherently not `Serializable`.

**Comment by non** [comment]
So I guess this is ultimately the `ExecutionContext`? I don't see any cases where `Monad[Future]` would be capturing a `Future[Int]` directly.

Maybe we need to make these tests conditional (so that `Monad[Future]` can opt-out)?

**Comment by adelbertc** [comment]
Ah yeah that makes sense, it's probably closing over that. Did you have a particular idea on how to have tests opt-out of the serializable test?

**Comment by non** [comment]
@adelbertc So -- one option would be to have a separate law/test class, and then explicitly call it in the tests (rather than having to automatically included). That would make serializability "opt-in".

Another option is to have an optional flag which disables that particular test. That would be "opt-out"

**Comment by non** [comment]
(Also -- thanks for this work! Feel free to hand it off if you want -- I'd be happy to try to hack something together.)

**Comment by non** [comment]
@adelbertc Seems like maybe there's a merge conflict. Would you mind manually merging and then pushing? Also, thanks for all this work -- patch is looking great.

**Comment by non** [comment]
:+1:

**Comment by ceedubs** [comment]
Thanks a bunch, @adelbertc. Java serialization is quite bewildering to me, but this looks like it should work, and it would be great to be able to make Cats Spark-friendly.

Looks like you need to merge master in again, but after that :+1:.

**Pull request merged**
