### PR TITLE
Minor cleanup in free monad doc

### PR DESCRIPTION
**Pull request by ceedubs**
This makes a couple small changes to the free monad docs.

1. Change most of the `tut` sheds to `tut:silent`. In most of these blocks, we are just defining objects/methods. There are only a few blocks where we are actually running things and care about the output. This makes things look a little cleaner.
2. One of the code blocks didn't use tut because it had a `readLine()` call that caused tut to hang. Unfortunately, this means that the code block wasn't compiler-verified, and it couldn't display its output. I've hacked around this by creating an invisible tut shed that defines `readLine` as a method that returns a canned String.

### CODE REVIEW

**Comment by ceedubs** [comment]
@raulraja what do you think about the canned string approach?

**Comment by non** [comment]
:+1:

**Comment by raulraja** [comment]
Looks great! Thanks for improving it! :+1:

**Comment by fthomas** [comment]
:+1:

**Pull request merged**
