### PR TITLE
add default implementation for lmap and rmap and add documentation for Profunctor

### PR DESCRIPTION
**Pull request by julien-truffaut**
I want to do more work on `Profunctor` but in the meantime I wanted to use this PR to discuss default implementation of TC.

I feel that in many cases it is rather arbitrary which method has a default implementation. I would prefer that we provide as many default implementation as possible and that we use the doc to say what is the minimum implementation required.

Also we should keep in mind that for many instances, it is more efficient to override the default implementation.

### CODE REVIEW

**Comment by ceedubs** [comment]
I'm a little wary of depending on documentation to make sure we don't accidentally forget to implement a required method. That's not to say I couldn't be talked into it, but do we have better alternatives?

What if we made the type class trait itself sealed but allowed you to extend one of two subtraits? There would be one where `dimap` is abstract and one where `lmap` and `rmap` are abstract. There may be better solutions, but that is one that came to mind.

**Comment by non** [comment]
Yeah I would strongly prefer that we leave at least one method abstract to avoid infinite loop / StackOverflowErrors.

I don't really like @ceedubs proposal, although I could be convinced to have a default type with `dimap` left abstract, and then a subtype in the companion which reverses the situation.

**Comment by julien-truffaut** [comment]
My biggest critic with the current setup is that it is extremely difficult to implement correctly and efficiently a TC hierarchy. Let's take `UpStar` as an example, we need to implement an instance of `Functor`, `Apply`, `Applicative` and `FlatMap` because if `F` is a `Monad` then `Upstar[F, A, ?]` is a `Monad` but if `F` is only an `Applicative` then `Upstar[F, A, ?]` is an `Applicative` but not a `Monad`.
In this hierarchy, `Functor`, `Apply` and `FlatMap` require a definition of `map` but `Monad` and `Applicative` provide a default implementation. So if we only implement the abstract method of each TC, we end-up with a `map` more efficient in a `Functor` than in a `Monad`.

This is related to #8

**Comment by xuwei-k** [comment]
Are `UpStar` and `DownStar` necessary?  `Kleisli[M[_], A, B](run: A => M[B])` and `Cokleisli[F[_], A, B](run: F[A] => B)` already exists.

**Comment by julien-truffaut** [comment]
@xuwei-k good point, I need to check if there is any difference in typeclass instance.

 It seems that `Kleisli` from scalaz has far more instances than the `Kleisli` from Haskell [Control-Arrow](http://hackage.haskell.org/package/base-4.7.0.2/docs/Control-Arrow.html). Do you know why are they different?

**Comment by non** [comment]
So my understanding was that the `Profunctor.upStar` and `Profunctor.downStar` methods were just to promote a `Functor[F]` into a `Profunctor[UpStar[F, ?, ?]]` -- they were not expected to be general types.

You can see them being used in [Data-Profunctor](https://hackage.haskell.org/package/profunctors-3.1.1/docs/Data-Profunctor.html), they are just newtypes with very few instances. I'm happy to remove them if they are unneeded but they seemed easy to implement.

For some reason I thought Kleisli's `M[_]` was intended to be a monad. I agree that in terms of the signatures we could just use `Kleisli` and `Cokleisli` there, if you don't think it will be confusing to folks.

**Comment by non** [comment]
(To Julien's more general point -- I agree that it's pretty ugly that we sometimes have to implement every *level* of a type class hierarchy. The example in algebra that hurts is map instances, where there end up being like 6-10 levels from semigroups up to commutative rngs.

I think using evidence instead of inheritance will be way too slow unfortunately. I would be interested to see tests which challenge this viewpoint but for now I think we are committed to inheritance.)

**Comment by xuwei-k** [comment]
> It seems that Kleisli from scalaz has far more instances than the Kleisli from Haskell Control-Arrow. Do you know why are they different?

http://ja.stackoverflow.com/a/6027/56

**Comment by julien-truffaut** [comment]
Cool, thanks for asking the question @xuwei-k 

Do I understand correctly that from 7.10, `Kleisli` and `UpStar` should have the same instances? It also seems that `UpStar` is more generic than `Kleisli` because it expects a `F[_]: Functor` but `Kleisli` usually expects a `Monad`. 

I might be completely wrong, please correct me.

**Comment by xuwei-k** [comment]
> Kleisli and UpStar should have the same instances? 

That's right. I think `UpStar` and `DownStar` is unnecessary in __Scala__ when there are `Kleisli` and `Cokleisli`.

**Comment by julien-truffaut** [comment]
is everyone fine if I rename `UpStar` to `Kleisli` and `DownStar` to `CoKleisli`?

**Comment by non** [comment]
We already have those types available in the project. I'm fine with removing `UpStar` and `DownStar` but we may need to reorganize a bit to use `Kleisli` and `Cokleisli`.

**Comment by julien-truffaut** [comment]
ah I didn't notice that we already have a `Kleisli` and `CoKlesili`.

I propose that I close this PR and restart from scratch, removing `UpStar`, `DownStar` and moving `Kleisli` and `Cokleisli` to data.

What do you think?

**Comment by non** [comment]
That sounds fine. Currently `UpStar` and `DownStar` are in the `core` project, so I think you'll either need to move them there, or you'll need to move the profunctor type classes elsewhere.

I'm fine if you want to start on this and see what you think is the best design. At this moment I'm not 100% sure where things should live.

**Comment by julien-truffaut** [comment]
ok let me give a try

**Pull request closed without merging**
