### PR TITLE
Fix StreamingT.filter bug

### PR DESCRIPTION
**Pull request by ceedubs**
As reported by @liff [here](https://gitter.im/non/cats?at=5694ce218fdd3c0c382e20f1).

### CODE REVIEW

**Comment by striation** [comment]
Wow! Jeez. Thanks @liff for catching this (and @ceedubs for the fix).

:+1:

**Comment by fthomas** [comment]
Any idea why this wasn't caught by the `"filter with Id consistent with List.filter"` test?

**Comment by ceedubs** [comment]
@fthomas I think because Scalacheck's auto-generated functions completely ignore their input and return a constant, so either the whole stream was filtered (`false`) or none of it was filtered (`true`). The effectiveness of these sorts of tests should improve once there is a new release of Scalacheck.

**Comment by xuwei-k** [comment]
LGTM https://github.com/xuwei-k/cats/commit/06e542d8f60583024fe902

**Comment by ceedubs** [comment]
Thanks @xuwei-k!

I'm going to go ahead and merge since this is a pretty obvious/straightforward bug.

**Pull request merged**
