### PR TITLE
applyN, tupleN, mapN in Apply up to 12 arity

### PR DESCRIPTION
**Pull request by wedens**
#61 i can add higher arity if required

### CODE REVIEW

**Comment by wedens** [comment]
maybe extract it into some trait with self type Apply? so Apply wouldn't be cluttered with all this arity methods

**Comment by non** [comment]
Yeah I'm interested in other people's opinions, but I think putting the higher arity methods in a different file/trait is appealing to me.

**Comment by stew** [comment]
Yeah, i think separating them is good.

**Comment by wedens** [comment]
simulacrum don't lets me extend typeclass with non-typeclass trait

**Comment by stew** [comment]
@wedens do you want to push up a commit that shows what you are seeing so @mpilquist can have a look?

**Comment by wedens** [comment]
reported issue to simulacrum https://github.com/mpilquist/simulacrum/issues/15

**Comment by non** [comment]
If you wanted to keep pushing on this I would be fine with removing the `@typeclass` annotation for now, and just adding the boilerplate manually. Since Simulacrum doesn't support shapes like `F[_, _]` we already have to do this for `Profunctor`, `Bifunctor`, etc.

**Comment by wedens** [comment]
@non if i remove `@typeclass` annotation on `Apply`, i'll be forced to remove it from any `Apply` subclasses. if you're ok with it, i'll do it.

**Comment by non** [comment]
I think that's fine. It should be easy to restore once @mpilquist (or one of us) has updated Simulacrum.

**Comment by wedens** [comment]
done. compilation fails after some changes in master

**Comment by ceedubs** [comment]
This has gone out of sync with master.

**Comment by wedens** [comment]
rebased on master

**Comment by wedens** [comment]
oh, sorry, just read on gitter that rebasing PRs is not welcome.

**Comment by non** [comment]
No worries -- I doubt anyone was basing their work on this branch. ;)

**Comment by ceedubs** [comment]
No worries. It hasn't made it into the contributor guide yet.

**Comment by ceedubs** [comment]
We may need to do some cleanup once mpilquist/simulacrum#15 is fixed, but I think this is good to merge. :+1:

**Comment by non** [comment]
:+1:

**Pull request merged**
