### PR TITLE
Released version on site

### PR DESCRIPTION
**Pull request by philwills**
Currently the site docs point to an old snapshot, this updates the docs to point to the currently released version instead.

### CODE REVIEW

**Comment by rossabaker** [comment]
:+1: 

Travis is failing repeatedly downloading sbt-launch.jar, and it's not immediately clear why.  I have to step out, but I'll look later if nobody beats me to it.

**Comment by xuwei-k** [comment]
https://github.com/travis-ci/travis-ci/issues/4527

**Comment by ceedubs** [comment]
:+1: thanks!

**Comment by non** [comment]
:+1: This doc fix looks good. I think we should just merge this now, the Travis failure seems unrelated.

**Pull request merged**
