### PR TITLE
Add Codecov support

### PR DESCRIPTION
**Pull request by InTheNow**
First tests on travis

### CODE REVIEW

**Comment by non** [comment]
:+1:
Since this isn't master I'll merge it once it's green.

**Comment by InTheNow** [comment]
@non  you might want to hold off a bit as I'm currently running local-ish tests - I'll ping when finished

**Comment by non** [comment]
Sounds good.

**Comment by travisbrown** [comment]
I can't check this locally because of "No source root found" errors apparently related to Scala.js, but I don't think mixing bare `build.sbt` syntax with multi-project actually does anything, does it? I'm pretty sure the `ScoverageKeys` settings need to go in `commonSettings`.

I'm also pretty sure `coverageExcludedPackages` needs to match the entire fully-qualified package name.

**Comment by InTheNow** [comment]
Here is the non scalajs version - https://codecov.io/github/InTheNow/cats?branch=fix/318 

>  actually does anything, does it?

Looks like it did actually do something

**Comment by travisbrown** [comment]
You'll get coverage reports because `sbt-scoverage` is an auto-plugin, but the explicit settings aren't having any effect. Try for example changing `coverageFailOnMinimum` to `true` and re-running. You won't get errors, but if you move all of the settings into `commonSettings`, you will.

**Comment by InTheNow** [comment]
@travisbrown I really appreciate your feedback on this, googling around shows you have had quite some experience on this!

re the scalajs issue, the tests here are only running in JVM mode, but the error is due to multiple shared roots, as the `shared` directory is... well shared. 

The main reason for trying this already on the `sjs` branch was to find issues - which we have.

**Comment by InTheNow** [comment]
right... I have a solution, will test on https://github.com/InTheNow/cats/branches first so you guys don't get spammed with my noise here, but can also see what I'm doing

**Comment by travisbrown** [comment]
Thanks for taking care of this, @InTheNow! Looking forward to getting it working!

**Comment by InTheNow** [comment]
Replaced by #331

**Pull request closed without merging**
