### PR TITLE
Xor and XorT recover and recoverWith

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by adelbertc** [comment]
Hmm not sure what the error is.. Scala.JS? SBT? @InTheNow

**Comment by stew** [comment]
:+1:

**Comment by travisbrown** [comment]
:+1: to both parts of this from me, but it might make more sense to split the build stuff into a separate PR?

**Comment by non** [comment]
I'm just going to merge this since it all looks good! :+1:

**Comment by InTheNow** [comment]
@travisbrown The reason the build parts were part of this PR is that the build only failed on Travis_CI _and_ in this PR.

**Pull request merged**
