### PR TITLE
Add ArbitraryK2, CategoryTests, and ComposeTests

### PR DESCRIPTION
**Pull request by fthomas**
This adds `CategoryTests` and `ComposeTests` and checks `Function1` against them. Since `Compose` and `Category` take a type constructor with two parameters, I had to add `ArbitraryK2` which is like `ArbitraryK` but for kinds `F[A, B]`.

### CODE REVIEW

**Comment by non** [comment]
I think this only works for covariant structures (like tuples, either, etc), but not for `A => B`.

Generating a *real* arbitrary `A => B` instance isn't simply a matter of generating some `A` and `B` values, but of creating a function where the `A` value determines which `B` value is generated. QuickCheck uses `CoArbitrary` for this:

https://hackage.haskell.org/package/QuickCheck-2.1.0.1/docs/Test-QuickCheck-Arbitrary.html#1

Currently ScalaCheck doesn't generate very good functions (it creates only constant functions that ignore their input) as you can see here:

https://github.com/rickynils/scalacheck/blob/master/src/main/scala/org/scalacheck/Arbitrary.scala#L305

However, I'd prefer that we not bake this into the design of `ArbitraryK2`. Does this make sense? We can still use the type, but we shouldn't provide the `Function1` instance.

**Comment by xuwei-k** [comment]
> Currently ScalaCheck doesn't generate very good functions

There is an issue in scalacheck https://github.com/rickynils/scalacheck/issues/136

**Comment by fthomas** [comment]
So for generating a real `A => B` a future version of ScalaCheck may require a `CoArbitrary[A]` (or something similar) instead of an `Arbitrary[A]`, and this does not match the `synthesize` signature in `ArbitraryK2`. But `ArbitraryK2` as it is now would still be useful for types like `Tuple2`, `Either`, etc. Ok that makes sense.

For some types it may also not so easy to provide an `ArbitraryK2`. For scalaz-stream's `Process1` for example, which has the same kind as `Function1` and is also a `Category`, it is easy to provide an `Arbitrary[Process1[A, A]]` (since there are a lot of different `Process1[A, A]`, see https://github.com/scalaz/scalaz-stream/blob/2a4a7b54d4366c79e46d7e622d398d1720000134/src/test/scala/scalaz/stream/TestInstances.scala#L23) but providing an `Arbitrary[Process1[A, B]]` would most likely mean to lift an arbitrary `A => B` into `Process1` and leaving out the most interesting `Process1[A, A]`s.

Now what do we do for `ComposeTests` and `CategoryTests`? Should we ask for the concrete `Arbitrary` instances explicity so that this:
```scala
  def compose[A: Arbitrary, B: Arbitrary, C: Arbitrary, D: Arbitrary](implicit
    ArbF: ArbitraryK2[F],
    EqFAD: Eq[F[A, D]]
  ): RuleSet = {
    implicit val ArbFAB = ArbF.synthesize[A, B]
    implicit val ArbFBC = ArbF.synthesize[B, C]
    implicit val ArbFCD = ArbF.synthesize[C, D]
```
becomes this:
```scala
  def compose[A, B, C, D](implicit
    ArbFAB: Arbitrary[F[A, B]],
    ArbFBC: Arbitrary[F[B, C]],
    ArbFCD: Arbitrary[F[C, D]],
    EqFAD: Eq[F[A, D]]
  ): RuleSet = {
```
? This way thoses tests can be used with ScalaCheck's `Arbitrary[A => B]` or scalaz-stream's `Arbitrary[Process1[A, A]]` without any additional code.

**Comment by non** [comment]
@fthomas Yes, I think your suggestion for `ComposeTests` and `CategoryTests` is what we'll have to do.

**Comment by fthomas** [comment]
I've updated `ComposeTests` and `CategoryTests` as outlined above and removed `ArbitraryK2`.

**Comment by non** [comment]
:+1:

**Comment by ceedubs** [comment]
:+1:

**Pull request merged**
