### PR TITLE
avoid creating objects in Xor map and leftMap

### PR DESCRIPTION
**Pull request by julien-truffaut**

### CODE REVIEW

**Comment by mpilquist** [comment]
:+1:

**Comment by non** [comment]
:+1: let's merge when Travis finishes

**Comment by rossabaker** [comment]
I looked into this when it was new, and to my surprise, couldn't measure any performance difference.  This was before we integrated better benchmarking tools, and this *seems* like it should help.

**Comment by non** [comment]
One thing that I've thought of since then is that you might notice this under memory pressure, in situations where there is other long-lived data and allocations might trigger more GC.

**Pull request merged**
