### PR TITLE
Add an overload of FlatMapOps#>> that gives control on the evaluation…

### PR DESCRIPTION
**Pull request by julienrf**
… strategy of the second action

### CODE REVIEW

**Comment by ceedubs** [comment]
On Gitter there was some discussion on whether to overload method names or use a consistent convention like an `Eval` suffix (such as `pureEval`) when an `Eval` alternative is provided. I like the idea of consistency, but that wouldn't work in the case of a symbolic operator like this one.

:+1: from me, but I'm hoping @travisbrown can weigh in, because I remember he mentioned being in favor of not overloading.

**Comment by julienrf** [comment]
I’m fine with adding a suffix like `Eval` but we need to find a real name for that method :)

**Comment by travisbrown** [comment]
[This SO answer](http://stackoverflow.com/a/2512001/334519) is a good summary of some of the reasons to avoid overloading. I personally think this is more important for things like `pure`—some of the big problems with overloading (eta expansion, selective imports) just aren't as relevant for instance methods, and operators like this seem to be one of the places where they're easier to justify.

Even here though it still introduces some annoying questions. Is `Eval.Unit >> Eval.now(Eval.True)` an `Eval[Eval[Boolean]]` or just an `Eval[Boolean]`? What if you actually want it to be the former?

**Comment by tpolecat** [comment]
In this case I think the subtlety introduced when `F` is `Eval` is sufficient reason to disambiguate.

**Comment by ceedubs** [comment]
Thanks @travisbrown. You have me convinced that disambiguating might be a good idea.

**Comment by julienrf** [comment]
Hi,

I totally agree on the issues of overloading. I will be happy to remove my overload and to introduce two new methods, on that is an alias for the current `>>` and the other, suffixed with `Eval`, with the new signature … as soon as we will have found a nice name :)

What about `discardAndThen`? `andAfter`? Other suggestions?

**Comment by julienrf** [comment]
Hi guys,

I decided to go with `andAfter` since monads are essentially about control flow. Tell me what you think :)

**Comment by non** [comment]
Interesting. I think that's a good name, but it made me think of `followedBy` which might be better. What do you think?

**Comment by julienrf** [comment]
I’m fine with `followedBy` too. What do others think?

**Comment by julienrf** [comment]
I updated the PR to use `followedBy`.

**Comment by non** [comment]
This looks good to me. :+1: 

Did you want to create an overload for `>>` so you can choose to pass an `Eval[F[B]]` as well as an `F[B]`? If so, I would support adding it.

**Comment by julienrf** [comment]
No, I gave up the idea of overloading.

**Comment by non** [comment]
:+1: from me then. Thanks for sticking with this! :)

**Comment by milessabin** [comment]
:+1:

**Pull request merged**
