### PR TITLE
changed bimap definition per chat with @non, @mpilquist

### PR DESCRIPTION
**Pull request by refried**

### CODE REVIEW

**Comment by non** [comment]
:+1:

**Comment by julien-truffaut** [comment]
Shall we also curry f and g as we did for dimap?

**Comment by ceedubs** [comment]
:+1:

My vote would be for getting this through and then deciding whether or not we want to curry separately.

**Comment by mpilquist** [comment]
Agreed -- opened https://github.com/non/cats/issues/147

**Pull request merged**
