### PR TITLE
Generate Apply methods up to arity 22; Factor out boilerplate generation...

### PR DESCRIPTION
**Pull request by stephenjudkins**
..., generalizing it.

Boilerplate generation mostly stolen from Shapeless. Originally written by Kevin Wright.

### CODE REVIEW

**Comment by milessabin** [comment]
That's a win :-)

The original is Apache2 licensed. @kevinwright, are you OK with this being included here under the MIT license?

**Comment by ceedubs** [comment]
Looks great to me. :+1: assuming @kevinwright is okay with the licensing.

At some point I think I'd like for us to document where/how we are using generated code -- probably both in the tut docs and in the ScalaDoc for the relevant files. I think generated code can be a bit confusing for people who tend to learn by reading the source, so a little heads up might be helpful.

**Comment by kevinwright** [comment]
I'm fine with this, let the code fly free!

**Comment by non** [comment]
Sounds great! :+1:

**Pull request merged**
