### PR TITLE
Run scalastyle in Travis CI script

### PR DESCRIPTION
**Pull request by ceedubs**

### CODE REVIEW

**Comment by travisbrown** [comment]
:+1:, but would you want to add `unidoc` here as well so we avoid problems like #89?

**Comment by non** [comment]
:+1: if we add unidoc

**Comment by travisbrown** [comment]
Note that #91 and #92 together means this will fail if merged now, because of trailing whitespace on line 8 of `examples/ApplyExamples.scala`. Mind adding that fix to this PR, @ceedubs?

**Comment by ceedubs** [comment]
@travisbrown done.

I remember people said they don't like rebasing once a PR is submitted, so I merged instead. Is that what I should be doing?

**Comment by non** [comment]
yes! that's great.

**Pull request merged**
