### PR TITLE
Increase git depth

### PR DESCRIPTION
**Pull request by InTheNow**

### CODE REVIEW

**Comment by ceedubs** [comment]
@InTheNow could you please provide a bit of explanation about why this is needed?

**Comment by InTheNow** [comment]
>  a bit of explanation about why this is needed? 

Ahh - good point. 

When travis does the `git clone` of master, it also sets `---depth=50` that creates a shallow clone of only the last 50 commits.

But for the `git describe` we need the tag on the first commit, which is 750 plus revisions. When a few releases/commits have been done, we can then remove this.

**Comment by ceedubs** [comment]
@InTheNow ah okay that makes sense. Thanks for the explanation.

:+1:

**Comment by fthomas** [comment]
LGTM. :+1: 

I don't think that we can remove this in the future. Whenever master is more than 50 commits ahead of the last tag, `git describe` will fail and therefore also the Travis builds. At least this was my experience with sbt-git.

**Comment by InTheNow** [comment]
Ok - maybe "remove" was a bit optimistic - perhaps just set to a more reasonable limit: say 1000

**Comment by fthomas** [comment]
Agreed. When things get more stable, we probably won't have 750+ commits between releases. :-)

**Pull request merged**
