### PR TITLE
Add State.pure

### PR DESCRIPTION
**Pull request by ceedubs**

### CODE REVIEW

**Comment by ceedubs** [comment]
Oops. I suppose I shouldn't decrease code coverage. Is there a meaningful test for this that isn't just a duplication of the implementation or an existing monad law?

**Comment by non** [comment]
I'm not sure. I guess my feeling is that you should just arrange to have it called somehow. Even just confirming that `State.pure[S, A](...)` and `StateT.pure[Trampoline, S, A](...)` are equivalent would be enough.

**Comment by ceedubs** [comment]
@non good idea. I added a test that State.pure and StateT.pure are consistent.

**Comment by ceedubs** [comment]
This is ready for review.

**Comment by non** [comment]
:+1:

**Comment by julien-truffaut** [comment]
:+1:

**Pull request merged**
