### PR TITLE
Rewrite OptionT.flatMap in terms of flatMapF

### PR DESCRIPTION
**Pull request by dwijnand**
.. and fix a typo I noticed.

### CODE REVIEW

**Comment by fthomas** [comment]
:+1: 

It seems the same could be done for `orElse` and `orElseF`.

**Comment by dwijnand** [comment]
@fthomas 

> It seems the same could be done for `orElse` and `orElseF`.

True, I had to check if by-name chain properly and they do, so added and updated the pull request.

**Comment by fthomas** [comment]
I haven't thought of a potential issue with the by-name params, so thanks for checking that. :+1:

**Comment by dwijnand** [comment]
For reference (and cross-checking), here's my proof:

```scala
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions to have them evaluated.
Type :help for more information.

scala> def foo(b: Boolean, default: => String) = if (b) println(default)
foo: (b: Boolean, default: => String)Unit

scala> def bar(default: => String) = foo(false, default)
bar: (default: => String)Unit

scala> def mkString: String = { println("making!"); "abc" }
mkString: String

scala> bar(mkString)

scala>
```

**Comment by ceedubs** [comment]
:+1: thanks!

**Pull request merged**
