### PR TITLE
Add a test for Show[Map]

### PR DESCRIPTION
**Pull request by mikejcurry**
Adds a test for Show[Map]

### CODE REVIEW

**Comment by ceedubs** [comment]
Thanks, @mikejcurry!

Since Simulacrum adds syntax for `Show` instances, it should be possible to just use `map.show` instead of bothering with `mapShow`. Would you want to give that a try?

**Comment by mikejcurry** [comment]
Sure, no problem - straightforward enough; I'll probably add a check that both approaches produce the same results also as it makes sense they produce consistent values. In most instances unlikely for anything to go wrong but a test shouldn't really hurt.

**Comment by ceedubs** [comment]
:+1:

**Comment by rossabaker** [comment]
:+1:

**Pull request merged**
