### PR TITLE
Use SBT doctest plugin

### PR DESCRIPTION
**Pull request by ceedubs**
This helps ensure that our ScalaDoc examples actually compile and
produce the expected result.

### CODE REVIEW

**Comment by ceedubs** [comment]
Resolves #487.

I think the only example I haven't converted is one in `MonadState`. This type class is part of `core`, but the example uses `StateT` which is in a separate module. I don't think there is a way to make the `core` tests depend on the `state` module, since the `state` module depends on `core`. If someone knows how to make that work, it would be great.

**Comment by ceedubs** [comment]
@fthomas would you be willing to review since you know doctest well? I'd also be interested in any input from @tpolecat, since you are great with docs and user-friendliness.

**Comment by mpilquist** [comment]
@ceedubs Are we still considering collapsing `free` and `state` in to `core`?

**Comment by ceedubs** [comment]
@mpilquist I haven't heard that come up recently. It does seem a little odd to me that `StateT` is currently in its own module but `WriterT` isn't (see #573). I haven't yet found myself really wishing that `Free` and `State` were in `core` (as I did with `std` back when it was separate), but I also haven't used Cats "in the real world" yet.

**Comment by ceedubs** [comment]
The builds failed. My guess is that it's because doctest brought in its own version of Scalacheck and I need to be explicit about using our version. I'll look into it.

**Comment by fthomas** [comment]
Since we are explicitly using ScalaCheck it is a good idea to not let sbt-doctest add ScalaCheck as a dependency with `doctestWithDependencies := false`, see https://github.com/tkawachi/sbt-doctest#note-for-librarydependencies

**Comment by fthomas** [comment]
I don't see any doctest output in the build log. I think we need to add `coreJVM/test` to the `buildJVM` alias.

**Comment by adelbertc** [comment]
This is awesome!

**Comment by ceedubs** [comment]
Wow, good eye, @fthomas. It should be fixed now.

**Comment by tpolecat** [comment]
This looks great. Makes me think how nice things would be if Travis were able to publish doc ... somewhere ... so reading doc in its final form could be part of the PR review process.

**Comment by ceedubs** [comment]
Okay I think this is good now. I see the following in the Travis build output:

```
[info] + Validated.scala.catchOnly.example at line 279: Validated.catchOnly[NumberFormatException] { "foo".toInt }: OK, proved property.
[info] + Xor.scala.catchOnly.example at line 227: Xor.catchOnly[NumberFormatException] { "foo".toInt }: OK, proved property.
[info] + OptionT.scala.fromOption.example at line 113: OptionT.fromOption[List](o): OK, proved property.
[info] + flatMap.scala.followedByEval.example at line 42: fa.followedByEval(Eval.later(fb)): OK, proved property.
[info] + XorT.scala.withValidated.example at line 130: xort.withValidated { v3 => (v1 |@| v2 |@| v3.leftMap(NonEmpt ...: OK, proved property.
[info] + XorT.scala.fromXor.example at line 156: XorT.fromXor[Option](t): OK, proved property.
[info] + Foldable.scala.traverse_.example at line 95: F.traverse_(List("333", "444"))(parseInt): OK, proved property.
[info] + Foldable.scala.traverse_.example at line 97: F.traverse_(List("333", "zzz"))(parseInt): OK, proved property.
[info] + Foldable.scala.foldK.example at line 142: F.foldK(List(1 :: 2 :: Nil, 3 :: 4 :: 5 :: Nil)): OK, proved property.
[info] + Foldable.scala.sequence_.example at line 122: F.sequence_(List(Option(1), Option(2), Option(3))): OK, proved property.
[info] + Foldable.scala.sequence_.example at line 124: F.sequence_(List(Option(1), None, Option(3))): OK, proved property.
```

**Comment by fthomas** [comment]
:+1: Great work, @ceedubs! I particular like that this shows which imports are necessary to bring the various instances into scope. Leaving out imports in examples can be frustrating for beginners and annoying for experts.

**Comment by ceedubs** [comment]
It sounds like there is general approval, so I'm going to go ahead and merge (in part because I'm hoping the changes to the `Arbitrary` instance for `Free` fix builds that are failing). I'm happy to make some followup changes if people have any to suggest.

**Pull request merged**
