### PR TITLE
Add Monad and Comonad instances for Function0

### PR DESCRIPTION
**Pull request by fthomas**

### CODE REVIEW

**Comment by ceedubs** [comment]
Thanks @fthomas! This looks great.

I think we might have the infrastructure in place to hook up at least FunctorLaws tests for this. Would you be willing to give that a try? If not, we can always create a separate issue to remind us to come back to the laws for this. (We'll have to come back to add Monad/Comonad laws anyway.)

**Comment by fthomas** [comment]
Yep, I'll look into it.

**Comment by fthomas** [comment]
@ceedubs The tests are now in place. I'll try to work on the Comonad laws next but would like to do it in a separate PR.

**Comment by non** [comment]
I think it makes sense to do the comonad laws in another PR.

**Comment by ceedubs** [comment]
Agreed about doing comonad laws in another PR.

:+1:

At some point we are probably going to want to split up the laws tests, but I think it's fine for now.

**Comment by non** [comment]
Looks like my other comment got lost. I give this :+1: and would be happy to merge this now and add more laws in another PR.

**Pull request merged**
