### PR TITLE
Turn on -Ywarn-unused-import

### PR DESCRIPTION
**Pull request by adelbertc**
Many thanks to @tpolecat for helping me turn off the setting for `tut`

### CODE REVIEW

**Comment by xuwei-k** [comment]
I recommend disable `"-Ywarn-unused-import"` when console. see http://stackoverflow.com/a/27858944/605582

**Comment by adelbertc** [comment]
Ah yes good point, thanks @xuwei-k

**Comment by ceedubs** [comment]
:+1:

**Comment by refried** [comment]
Instead of adding it and then removing it, might want to just add it for the compile phase:
`scalacOptions in compile += "-Yno-imports"`

**Comment by dwijnand** [comment]
The benefit of the adding and removing is more about have the opinion that you always want it enabled, but then selectively, explicitly disable it where (for now) necessary.

**Comment by non** [comment]
:+1:

**Pull request merged**
