### PR TITLE
Backfill several missing `cats.std._` tests

### PR DESCRIPTION
**Pull request by rossabaker**
* Introduce `MonadCombineTests`.  No unique laws, but covers its parents.
* Backfill some missing tests for standard instances.
* There still exists a big testing gap on `Traverse`.

#218

### CODE REVIEW

**Comment by non** [comment]
:+1: 

and yeah we need to cover traverse asap

**Comment by mpilquist** [comment]
@rossabaker What about distributivity of `flatMap` over `combine`: https://github.com/mpilquist/Structures/blob/9b35e827f7d83cc73a2715bd293e8712e2c42675/laws/src/main/scala/structures/laws/MonadCombineLaws.scala

**Comment by mpilquist** [comment]
Also, note that `MonadCombine` and `MonadCombineLaws` are dependent on `Alternative`, which isn't present in cats yet. `Alternative` defines a number of laws: https://github.com/mpilquist/Structures/blob/9b35e827f7d83cc73a2715bd293e8712e2c42675/laws/src/main/scala/structures/laws/AlternativeLaws.scala

**Comment by rossabaker** [comment]
Traverse (and Foldable) gap noted in #224.

**Comment by rossabaker** [comment]
I now see that this is related to #135.

I want `MonadCombineTests` now so `MonadCombine` instances are held to any forthcoming laws.  I'll leave any additional legislation to #135 or possible future inheritance from #225.

**Comment by ceedubs** [comment]
:+1:

**Pull request merged**
