### PR TITLE
Add tut doc for State

### PR DESCRIPTION
**Pull request by ceedubs**
It still needs a little work explaining StateT and State's use of
Trampoline, but I figured it would be best to get something out there.

If you want to see the formatted version, it's currently posted [here](http://non.github.io/cats//tut/state.html). Sorry, I tried to push it to the gh-pages branch on my fork instead of the official repo, but apparently just changing `git.remoteRepo` in `build.sbt` isn't enough :(

### CODE REVIEW

**Comment by ceedubs** [comment]
Fixes #314.

**Comment by ceedubs** [comment]
I just got the following feedback from a coworker:

> I read it and was left thinking what does state give you.

I think maybe I should draw a bit more attention to the fact that you could do the manual state threading without State, but that State allows the nice imperative syntax you see at the end of the tutorial.

**Comment by non** [comment]
For a simple example I suggest an RNG. People are familiar with mutable RNGs, and it's easy to show why code that manually threads immutable RNG state is somewhat ugly.

**Comment by non** [comment]
I think before showing the State-based code, you should show the code that manually threads an immutable RNG. I think this helps motivate the problem.

**Comment by ceedubs** [comment]
@non I agree. I'll revisit this. Might not be until this weekend.

**Comment by ceedubs** [comment]
Closing this for now until I've reworked things a bit. I expect to submit it again this weekend.

**Pull request closed without merging**
