### PR TITLE
Add Scalastyle

### PR DESCRIPTION
**Pull request by ceedubs**
This addresses one of the requests made in #50.

I just kind of went with rules that seemed right for the project. People are free to suggest changes.

Currently one has to explicitly run the `scalastyle` or `test:scalastyle` task to check style. Adding linting to the compile task would probably be too slow. We could potentially add it to the test task, but I gave that a quick try and was having some trouble getting it to check the main source in addition to the test source with that approach. Once we have Travis CI integration, we should be able to run the linting without slowing down our compile or test tasks. It might still be worth making one uber sbt task to test and run linting, and I would encourage someone who understands SBT much better than I do to do so! :)

### CODE REVIEW

**Comment by travisbrown** [comment]
This looks great to me—thanks for putting it together. I don't see a strong need for Scalastyle to run in the test task—we don't want to slow things down until the configuration is settled—but [here's a quick example](https://github.com/travisbrown/cats/commit/b882ae15c032a179a38acdbacc23cef86129aab4) of how you could do it if you wanted to.

**Comment by non** [comment]
This seems good for now. We may want to relax some of these (or add more) as we hit issues, but for now I think it's a good default. :+1:

**Comment by stew** [comment]
:+1:

**Comment by ceedubs** [comment]
Does anyone know what we need to do to make the Travis builds run scalastyle and validate that no errors are detected?

**Comment by travisbrown** [comment]
`script: "sbt test scalastyle"` should do it.

**Pull request merged**
