### PR TITLE
fixes #181: add FreeApplicative

### LINKED ISSUE #181: Add FreeApplicative Functor

### PR DESCRIPTION
**Pull request by mandubian**

### CODE REVIEW

**Comment by non** [comment]
This is largely the same as what you have here but I feel like this code might be a bit more approachable in some ways: https://gist.github.com/non/9d744882afa07b715abe

What do you think? Basically, I feel like the current code exposes the `Pivot` more than is really needed.

Feel free to disregard this gist -- this was just me sort of backseat driving a bit :P

**Comment by wedens** [comment]
Example will be very appreciated

**Comment by mandubian** [comment]
yes sure & doc too.
I'll add that

**Comment by ceedubs** [comment]
@mandubian has #205 replaced this?

**Comment by mandubian** [comment]
Yes... Let's close this one & study the merge of #205. 
Maybe, you could merge #205 as it is and then we could move free to data or something like that and then go on working on Free docs.
WDYT?

**Comment by ceedubs** [comment]
@mandubian thanks. See https://github.com/non/cats/pull/205#issuecomment-76526064

**Pull request closed without merging**
