### PR TITLE
Add Choice type class, closes #463 redux

### LINKED ISSUE #463: add cats.arrow.Choice
see [scalaz.Choice](https://github.com/scalaz/scalaz/blob/series/7.2.x/core/src/main/scala/scalaz/Choice.scala)

required for https://github.com/julien-truffaut/Monocle/issues/235

### PR DESCRIPTION
**Pull request by adelbertc**
Accidentally merged previous, reverted that one. See https://github.com/non/cats/pull/468 for previous discussion.

### CODE REVIEW

**Comment by julien-truffaut** [comment]
`Choice` is actually missing

**Comment by julien-truffaut** [comment]
@fthomas as far as I can see, the only reason why `scalaz.Choice` inherit `Category` and not `Compose` is `codiagonal` https://github.com/scalaz/scalaz/blob/series/7.2.x/core/src/main/scala/scalaz/Choice.scala#L15

**Comment by fthomas** [comment]
Hmm, okay. I looked through our current type classes and noted that we have a similar situation with `MonadFilter`. The `MonadFilterLaws` only make use of `empty` and `flatMap` which suggests that `MonadFilter` should actually be called `FlatMapFilter` and inherit `FlatMap`, but `MonadFilter` has derived functions that are implemented in terms of `flatMap`, `pure`, and `empty` (like `diagonal` in this case).

Under the assumption that we tolerate such artificial dependencies, I'm fine with `Choice` as it is right now.

**Comment by julien-truffaut** [comment]
@adelbertc there is no `Choice.scala` in the changelist

@fthomas good point, I am fine either way: remove `diagonal` and inherit from `Compose` or let it is as it is. We should probably create an issue to discuss this general situation and get feedback from other

**Comment by fthomas** [comment]
@julien-truffaut Sounds good to me. I'm slightly in favor of keeping `diagonal` for now.

**Comment by non** [comment]
Let's leave it as-is (once @adelbertc re-adds `Choice.scala` that is). :+1:

**Comment by julien-truffaut** [comment]
:+1:

**Pull request merged**
