### PR TITLE
better test coverage for kleisli

### PR DESCRIPTION
**Pull request by woparry**
As an aside, this test illustrates a general problem with the current architecture for test coverage.

Rather than having a single object/piece of code which is the typeclass instance for all typeclasses, we have separate implicit code/objects for each refinement. This means that we have to explicitly pull in and run the laws on each to get test coverage - something that discipline could normally take care of for us via 'parents' etc.

What's the reasoning behind the disparate instances?

(NB: please don't consider this a blocker for improving test coverage; I'm happy to add this code and remove it later if it turns out we don't need it. As long as the different instances have different implementations, we need to test them all.)

### CODE REVIEW

**Comment by ceedubs** [comment]
@woparry I'm trying to better understand the issue you are describing.

> This means that we have to explicitly pull in and run the laws on each to get test coverage - something that discipline could normally take care of for us via 'parents' etc.

As I understand it, when you check the monad laws for Kleisli you _are_ automatically checking the applicative and flatMap laws as well. Am I right about that? Is this a separate matter than what you are referring to?

It looks like currently the approach is to test all of the monad laws but separately check the applicative laws with an instance that isn't declared as a full monad. I guess that we do kind of need this separate check (and it might be particularly helpful to use `Validated` or something else that has an Applicative but no Monad instance). It does look pretty verbose though. Is this the problem to which you are referring?

**Comment by ceedubs** [comment]
PS: thanks for the help with code coverage!

**Comment by non** [comment]
I think @woparry is complaining about the fact that to completely cover all our code, we have to test that the type classes returned by `kleisliArrow`, `kleisliSplit`, and `kleisliStrong` are consistent, as well as 
`kleisliMonad`, `kleisliFlatMap`, `kleisliApplicative`, `kleisliApply`, and `kleisliFunctor`. Since each of these implicit methods instantiates a different class, we do have to check them individually.

Unfortunately, I think we do have to manually test these. The reason we support these disparate instances is that the requirements are different. For example, if we have a `Monad[F]` we can get an `Arrow[Kleisli[F, ?, ?]]` but if we only have a `Functor[F]` we can only get a `Strong[Kleisli[F, ?, ?]]`. Since `Arrow[Kleisli[F, ?, ?]]` is *also* a valid `Strong[Kleisli[F, ?, ?]]` we have to use implicit priority to ensure the two methods never become ambiguous. Unfortunately this means that unless you "hide" your `Monad[F]` you will only ever use `kleisliArrow`, even if you want to test `kleisliStrong`.

Sorry if that was all obvious to folks. I just wanted to explain what is going on here. @woparry I don't see a good alternative way to structure this (and test all our code). Is there something else we could be doing here?

**Comment by non** [comment]
Incidentally, :+1: on this PR. It needs to be updated though.

**Comment by woparry** [comment]
That explanation makes sense, thanks. No alternative structure is obvious.

It does suggest we might want tests for the implicit precedence structure, though. I'll think on those and make a follow-up PR if anything comes of it.

**Comment by ceedubs** [comment]
:+1:

Thanks @woparry!

**Pull request merged**
