### PR TITLE
Prefix laws with the name of their typeclass

### PR DESCRIPTION
**Pull request by fthomas**
Since laws are mixed in, this helps preventing name clashes, and it makes the Scaladoc more clear since the laws are then grouped by their typeclass, see:
http://non.github.io/cats/api/#cats.laws.MonadCombineLaws

The second commit removes an unnecessary test because the `alternative` `RuleSet` is included in the `monadCombine` `RuleSet`.

### CODE REVIEW

**Comment by non** [comment]
:+1:

**Comment by mpilquist** [comment]
:+1:

**Comment by mpilquist** [comment]
@fthomas Can you update this PR based on master?

**Comment by fthomas** [comment]
@mpilquist Updated. I wish GitHub would notify me if a PR can't be merged automatically anymore.

**Pull request merged**
