### PR TITLE
Issue #63

### PR DESCRIPTION
**Pull request by coltfred**
First crack at comments on Foldable. Fix for #63.

### CODE REVIEW

**Comment by mpilquist** [comment]
:+1: 

Looks good. Some minor consistency things, like punctuation on each doc (some have it whereas some don't). Also, probably would be good to add backticks around the types in the docs. E.g., `Monoid[F]` instead of Monoid[F].

**Comment by non** [comment]
Looks good to me. :+1: 

(I like these kinds of small incremental PRs which are easy to approve, can be built on later.)

**Comment by non** [comment]
@mpilquist What is the proper ScalaDoc thing to delimit types? Do backticks work?

**Comment by coltfred** [comment]
Let me know what the approved way to do the type delimit types is and I'll fix the punctuation.

**Comment by non** [comment]
I'm just going to merge this now and we can fix it all once we decide the right way to do it.

**Pull request merged**
