### PR TITLE
setup tut, sbt-site, sbt-ghpages

### PR DESCRIPTION
**Pull request by stew**
this gets our docs into the main tree under a new docs sub-project
we can place md files under docs/src/main/tut, tut will compile the tut sections
these tut compiled .md files are combined with files under docs/src/site, and with the scaladoc

docs/ghpages-push-site will push all our docs to https://non.github.io/cats

### CODE REVIEW

**Comment by tpolecat** [comment]
Works. :+1: 

I will follow up with stuff to generate the table of contents, and will clean up the existing tut sheds (some of the blocks would look better with `tut:silent`).

**Comment by ceedubs** [comment]
I've created https://github.com/stew/cats/pull/1 to ensure that changes that break docs get caught by Travis. After that, :+1: x :100:

**Comment by non** [comment]
Yeah :+1: from me as well once @ceedubs's thing is merged.

Great work!!!

**Comment by non** [comment]
:+1: after travis i'll merge this

**Pull request merged**
