### PR TITLE
Add Foldable.exists

### PR DESCRIPTION
**Pull request by ceedubs**
And override it on some std lib structures for efficiency.

### CODE REVIEW

**Comment by non** [comment]
:+1:

Should we add `forall` too? I feel like if one of those methods is provided I like seeing the other too (I feel the same way about `compose` and `andThen`).

**Comment by ceedubs** [comment]
I added `forall` and `empty` to `Foldable`

I also added tests/laws that forall and exists are lazy. This
laziness is probably more of a suggested implementation feature
rather than a _law_. However, since people will probably always
want their structures to follow this suggestion, I've added it to
the laws so mistakes are easily caught. I'm open to the idea that
this constraint shouldn't be enforced.

**Comment by non** [comment]
I support the laziness tests for now. As you say, we can always relax those, but they are clearly part of the spirit of the type class.

:+1:

**Comment by rossabaker** [comment]
:+1:

**Pull request merged**
