### PR TITLE
std.string

### PR DESCRIPTION
**Pull request by tpolecat**
Ha, ok. Didn't realize that `Show` was literally the only thing to do ... `Monoid` and so on are in algebra. Oh well. Here you go.

### CODE REVIEW

**Comment by lvicentesanchez** [comment]
Isn't this a duplicate of #56 ?

**Comment by tpolecat** [comment]
Oh, I guess it is. Looks like I assigned #52 to myself and in the meantime @mandubian implemented it. Let's try to be more careful with the tickets and stuff to avoid duplicated work (although admittedly this wasn't much).

**Comment by mandubian** [comment]
sorry, I had just done that in 10mn to start contributing something...

**Comment by tpolecat** [comment]
no worries

**Pull request closed without merging**
