### PR TITLE
Failed to update the README for 0.2.0. Oops.

### PR DESCRIPTION
**Pull request by non**

### CODE REVIEW

**Comment by fthomas** [comment]
Can you also update the version in docs/src/site/index.md?

**Comment by non** [comment]
I tried to only summarize uncontentious policy that we all agree with, but if I mischaracterized anything I am happy to change it. Mostly, I wanted to try to create a repository for the knowledge of how to do releases so I won't forget to update that file every single time.

**Comment by adelbertc** [comment]
:+1: awesome

**Comment by fthomas** [comment]
:+1:

**Pull request merged**
