### PR TITLE
more examples for Foldable

### PR DESCRIPTION
**Pull request by rintcius**
More examples for `Foldable`. 

I don't like the `sequence_` and `traverse_` examples that much. Happy to hear something better!

### CODE REVIEW

**Comment by non** [comment]
These look good to me. I'd be happy to merge these now if you want to open an issue with some thoughts on what could make the foldable docs ever better.

**Comment by rintcius** [comment]
@non created https://github.com/non/cats/issues/508

**Comment by non** [comment]
:+1:

**Comment by fthomas** [comment]
:+1:

**Pull request merged**
