### PR TITLE
Add MonadState, instance for StateT

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by ceedubs** [comment]
Forgive me for the ignorant question. If `StateT` is the only type that implements `MonadState`, then is this abstraction useful? I could see it being more useful if we also had an `RWST`. Are we just working under the assumption that Cats will have something like RWST in the future? Or are we providing this abstraction because we think other people might have custom monads with state components that they want to abstract over?

@adelbertc @travisbrown

**Comment by adelbertc** [comment]
I had the same thoughts myself - I guess I could see it being useful with a large StateT stack where using the StateT `get` and `set` methods got tedious when it has trouble unifying the `F[_]` param so you could just do something like:

```scala
val M = MonadState[GiantStateTStack, S, ?]

/** Use M.get and M.set here */
```

Not a particularly strong argument I think.

Not sure what the verdict is on adding a `Writer` to cats, but given we have `Reader` and `State` I could see having an `RST`.

**Comment by stew** [comment]
Yes, this is useful when you get syntax, in @adelbertc's example, you can also just `import M._`, then you get to write a nice for comprehension:

```scala
import M._
val addOne = for {
    s <- ask
    s2 = s + 1
    _ <- put(s2)
} yield ()
```

This probably deserves an example, though I give this the :+1:

**Comment by travisbrown** [comment]
Probably 95% of the time I've used `MonadState` in Scala it's been to make working with `StateT` less painful (as in @adelbertc and @stew's examples).

It's a bit of a shame I guess to (mis)use a type class that's intended to support abstraction almost entirely to clean up syntax, but it works, people are familiar with it, etc. So :+1: from me.

**Comment by ceedubs** [comment]
Sounds good. Thanks for the input everyone (and especially @adelbertc for the contribution).

**Pull request merged**
