### PR TITLE
More unapply

### PR DESCRIPTION
**Pull request by stew**
Adds some unapply shapes for monad transformers.

Uses unapply for most bedazzlers into syntax.

### CODE REVIEW

**Comment by tpolecat** [comment]
So, scalaz has both "normal" and [lower-priority] unapply versions of all the syntax bedazzlers. I wonder if there is any downside to only having the unapply versions.

**Comment by stew** [comment]
yeah, I noticed this, but was unable to come up with a time that we care, since I don't think there is a situation where the straight version matches but not the unapply version.

If we were to have ImplicitNotFound tags that did anything here (I'm not sure they would), then perhaps I'd add back the other bedazzlers, as the ImplicitNotFound messages the come from Unapply instances tend to not be very newcomer friendly.

**Comment by ceedubs** [comment]
I think in addition to being newcomer friendly, the other benefit of the non-Unapply versions is that they don't incur the overhead of `Unapply` allocations.

**Comment by non** [comment]
Yeah, I guess I lean towards agreeing with @ceedubs here, but don't have strong opinions.

**Comment by stew** [comment]
yeah, that makes sense. I'll add the non-unapply versions this evening. thanks!

**Comment by ceedubs** [comment]
Scalastyle:
> apply.scala:11:70: Whitespace at end of line

Other than that, this looks good to me. We probably should add some unit tests to make sure things work the way that we would expect.

**Comment by non** [comment]
:+1:

**Pull request merged**
