### PR TITLE
Fix git described snapshots on 2.10

### PR DESCRIPTION
**Pull request by InTheNow**
Original version lost build settings when new state created

### CODE REVIEW

**Comment by dwijnand** [comment]
Interesting, why does the former not work?

**Comment by non** [comment]
:+1:

**Comment by milessabin** [comment]
:+1:

**Comment by InTheNow** [comment]
@dwijnand When `++2.10.5` is called, followed by a call to a new state, the scala version is lost as it is not stored in the state 

Using the current master, in SBT:

```sbt
++2.10.5
[info] Setting version to 2.10.5
[info] Reapplying settings...
[info] Set current project to cats (in build file:/home/alistair/prj/git/ws/cats/cats.itn.master/)
> show scalaVersion
[info] tests/*:scalaVersion
[info]  2.10.5
[info] core/*:scalaVersion
[info]  2.10.5
[info] std/*:scalaVersion
[info]  2.10.5
[info] bench/*:scalaVersion
[info]  2.10.5
[info] free/*:scalaVersion
[info]  2.10.5
[info] state/*:scalaVersion
[info]  2.10.5
[info] laws/*:scalaVersion
[info]  2.10.5
[info] docs/*:scalaVersion
[info]  2.10.5
[info] macros/*:scalaVersion
[info]  2.10.5
[info] cats/*:scalaVersion
[info]  2.10.5
> show version
[info] tests/*:version
[info]  0.1.3-SNAPSHOT
[info] core/*:version
[info]  0.1.3-SNAPSHOT
[info] std/*:version
[info]  0.1.3-SNAPSHOT
[info] bench/*:version
[info]  0.1.3-SNAPSHOT
[info] free/*:version
[info]  0.1.3-SNAPSHOT
[info] state/*:version
[info]  0.1.3-SNAPSHOT
[info] laws/*:version
[info]  0.1.3-SNAPSHOT
[info] docs/*:version
[info]  0.1.3-SNAPSHOT
[info] macros/*:version
[info]  0.1.3-SNAPSHOT
[info] cats/*:version
[info]  0.1.3-SNAPSHOT
> gitSnapshots
[info] Set current project to cats (in build file:/home/alistair/prj/git/ws/cats/cats.itn.master/)
> show version
[info] tests/*:version
[info]  v0.1.2-15-gc78c60a-SNAPSHOT
[info] core/*:version
[info]  v0.1.2-15-gc78c60a-SNAPSHOT
[info] std/*:version
[info]  v0.1.2-15-gc78c60a-SNAPSHOT
[info] bench/*:version
[info]  v0.1.2-15-gc78c60a-SNAPSHOT
[info] free/*:version
[info]  v0.1.2-15-gc78c60a-SNAPSHOT
[info] state/*:version
[info]  v0.1.2-15-gc78c60a-SNAPSHOT
[info] laws/*:version
[info]  v0.1.2-15-gc78c60a-SNAPSHOT
[info] docs/*:version
[info]  v0.1.2-15-gc78c60a-SNAPSHOT
[info] macros/*:version
[info]  v0.1.2-15-gc78c60a-SNAPSHOT
[info] cats/*:version
[info]  v0.1.2-15-gc78c60a-SNAPSHOT
> show scalaVersion
[info] tests/*:scalaVersion
[info]  2.11.7
[info] core/*:scalaVersion
[info]  2.11.7
[info] std/*:scalaVersion
[info]  2.11.7
[info] bench/*:scalaVersion
[info]  2.11.7
[info] free/*:scalaVersion
[info]  2.11.7
[info] state/*:scalaVersion
[info]  2.11.7
[info] laws/*:scalaVersion
[info]  2.11.7
[info] docs/*:scalaVersion
[info]  2.11.7
[info] macros/*:scalaVersion
[info]  2.11.7
[info] cats/*:scalaVersion
[info]  2.11.7
> 

```

**Comment by dwijnand** [comment]
I see, thank you.

**Pull request merged**
