### PR TITLE
Introduce IsEq as return type for laws

### PR DESCRIPTION
**Pull request by fthomas**
This PR adds a new type `IsEq` to the `cats.laws` package that is used as return type for all laws we currently have. `IsEq` represents two values of the same type that are expected to be equal. It replaces the current usage of `scala.Tuple2` (e.g. `(F[A], F[A])` becomes `IsEq[F[A]]`). I've also added an implicit conversion to easily create an `IsEq` via the `<->` operator. These two changes are purely aesthetic.

The interesting bit of this PR is the implicit conversion in the `discipline` package object that converts any `IsEq[A]` given an `Eq[A]` to a ScalaCheck `Prop` which can pretty print the values of an `IsEq` in case of an error. This allows to pass the laws directly to ScalaCheck's `forAll`, e.g. `forAll(FunctorLaws[F].covariantIdentity[A] _)`.

The reason for not using `Prop` as return type for the laws is that this would mean adding `implicit Eq[...]` parameters to every law there is which I find ugly. I also value the fact that the laws (as they are defined now) are independent of any test framework.

P.S.: Thanks to all people on gitter for providing feedback on this topic.

### CODE REVIEW

**Comment by non** [comment]
:+1: looks great

**Comment by stew** [comment]
:+1:

**Comment by fthomas** [comment]
Sorry for adding commits to this PR, but there were merge conflicts that needed to be resolved. I also took the opportunity to adapt `coFlatMapAssociativity` to the new naming scheme.

**Comment by non** [comment]
Still looks good -- merging now.

**Pull request merged**
