### PR TITLE
add benchmark module using jmh with an example

### PR DESCRIPTION
**Pull request by julien-truffaut**
here are two run of the same benchmark, first one with default options that are probably overkilled and second one with a more reasonable settings

```
sbt
project bench
run
[info] # Warmup: 20 iterations, 1 s each
[info] # Measurement: 20 iterations, 1 s each
[info] # Timeout: 10 min per iteration
[info] # Threads: 1 thread, will synchronize iterations
[info] # Benchmark mode: Throughput, ops/time
[info] # Benchmark: cats.bench.FoldBench.fold
...
[info] Result: 256072.056 ±(99.9%) 6923.698 ops/s [Average]
[info]   Statistics: (min, avg, max) = (209014.993, 256072.056, 339053.906), stdev = 29315.372
[info]   Confidence interval (99.9%): [249148.357, 262995.754]
[info] 
[info] 
[info] # Run complete. Total time: 00:13:32
[info] 
[info] Benchmark                 Mode  Cnt       Score       Error  Units
[info] FoldBench.fold           thrpt  200  614594.996 ± 18809.231  ops/s
[info] FoldBench.traverseConst  thrpt  200  256072.056 ±  6923.698  ops/s
[success] Total time: 818 s, completed 12-Feb-2015 21:58:33
```

```
sbt
project bench
run -i 10 -wi 5 -f3 -t1

[info] # Warmup: 5 iterations, 1 s each
[info] # Measurement: 10 iterations, 1 s each
[info] # Timeout: 10 min per iteration
[info] # Threads: 1 thread, will synchronize iterations
[info] # Benchmark mode: Throughput, ops/time
[info] # Benchmark: cats.bench.FoldBench.fold
...
[info] Result: 234657.170 ±(99.9%) 7253.338 ops/s [Average]
[info]   Statistics: (min, avg, max) = (203685.003, 234657.170, 251857.185), stdev = 10856.456
[info]   Confidence interval (99.9%): [227403.832, 241910.509]
[info] 
[info] 
[info] # Run complete. Total time: 00:01:33
[info] 
[info] Benchmark                 Mode  Cnt       Score       Error  Units
[info] FoldBench.fold           thrpt   30  645640.406 ± 34900.382  ops/s
[info] FoldBench.traverseConst  thrpt   30  234657.170 ±  7253.338  ops/s
[success] Total time: 98 s, completed 12-Feb-2015 22:05:21
```

### CODE REVIEW

**Comment by julien-truffaut** [comment]
separate issue, `foldLeft` returns "abc...z" while `traverse` returns "zwyx...a"

**Comment by non** [comment]
:+1: thanks!

i'll look into the other issue now (and add some more tests).

**Comment by refried** [comment]
I'm excited about caring about benchmarks!

**Comment by ceedubs** [comment]
Fantastic. Thanks, @julien-truffaut!

**Comment by fthomas** [comment]
Awesome that cats cares about performance early on!

**Pull request merged**
