### PR TITLE
Add OptionT monad transformer

### PR DESCRIPTION
**Pull request by ceedubs**
This currently lacks documentation, tests, and many type class instances. I
thought I would get it out there for review, and I (or others) can
polish it if people generally agree this should exist.

### CODE REVIEW

**Comment by non** [comment]
This seems good to me. :+1: 

I'd prefer additional commits to add tests and docs, but I would be fine merging this and doing those in a follow-up issue/PR.

**Comment by stew** [comment]
all of what Erik said...

**Comment by non** [comment]
@stew So is that a +1 from you? Should I merge this?

**Comment by ceedubs** [comment]
It's up to others, but my suggestion might be to let it hang for now. I mostly just wanted to get confirmation that this was something people thought was worth having in Cats. Things are really busy for me right now, but I'm hoping that within the next couple weeks I can add some docs/tests for State and then for this.

**Comment by ceedubs** [comment]
It's also completely fine if people would rather have it merged. It's just more likely that I'll forget to return to it :)

**Comment by non** [comment]
I'm fine with either -- but one advantage to merging it now is that it gives someone else an obvious way to get involved helping to document/test/clean up these types.

**Comment by ceedubs** [comment]
That makes sense. That sounds good to me. I'm not protective of documentation/test/cleanup work :)

**Comment by woparry** [comment]
I don't think toLeft and toRight should be here - rather they should be on the XorT companion or something. You're likely to want them if you're importing XorT (because you're using Xor) and not want them otherwise - they just clutter this up.

If XorT was still in data we would not be considering these.

**Comment by ceedubs** [comment]
I'm interested to hear what others think about `toLeft` and `toRight`. I use these methods very often, but maybe I'm alone in that.

**Comment by woparry** [comment]
To be clear, I'm very happy to have these methods exist, I just think they should be provided via enhance-my-library when XorT is imported so that OptionT doesn't depend (unnecessarily) on data.

**Comment by non** [comment]
So -- I thought `OptionT` was actually put in `cats.data` but now I see it is in `cats.std` instead.

What's the rationale for that?

**Comment by ceedubs** [comment]
@non I guess my thought was that it's support for a standard lib type (Option).

**Comment by non** [comment]
@ceedubs So, my view (which may not be shared by most of the other Cats cats) is that `std` really just means type class instances for standard library types (possibly stretched to include types of a module's other dependencies as well). By this rationale, I think things like `OptionT`, `StreamT`, etc. would belong in `cats.data` (or elsewhere).

What does everyone else think? :cat2:

**Comment by ceedubs** [comment]
@non I don't have strong opinions on this (and as I've mentioned elsewhere, think that std should probably be merged into core anyway). I'm happy to switch it over. I'll give a bit of time for others to weigh in.

We may find that `data` is a bit of a wide net to throw. But I guess we can just keep an eye on that, and if it starts to look like it's getting bloated, we can break it down.

**Comment by ceedubs** [comment]
I just added a bunch of `OptionT` tests and moved it from `std` to `core/data`. Based on feedback provided on this PR, I'd be inclined to go with merging this and I can create a new issue for following up with documentation.

**Comment by ceedubs** [comment]
I added some documentation and changed `collect`, `filter`, and `filterNot` to return `OptionT`. @non @stew what do you think?

**Comment by non** [comment]
Looks good to me. :+1:

I could imagine importing syntax and writing more of the `OptionT` code to use `[B: Functor]` instead of `(implicit ev: Functor[B])` but let's just merge it as-is.

**Comment by adelbertc** [comment]
:+1: yay for tut documentation!

**Pull request merged**
