### PR TITLE
I hit these problems trying to get started with cats during Stew's SBTB talk

### PR DESCRIPTION
**Pull request by SethTisue**
please sanity-check the `catsJVM/publishLocal` part, I think it's right,
but I did a bunch of fumbling around before hitting on it and it's possible
it isn't enough by itself

### CODE REVIEW

**Comment by SethTisue** [comment]
oh, hmm, this should maybe not be accepted. in the readme on the master branch, it recommends using "0.1.2" rather than building from source and doing publishLocal.

**Comment by non** [comment]
I'm going to close this, since it seems like the README is currently providing correct instructions. Does that make sense @SethTisue?

**Comment by SethTisue** [comment]
But http://non.github.io/cats/ is currently providing incorrect instructions. And there's a meta-issue, that there are two different sets of getting started instructions at all. I'm just not sure what the right fix is, from the maintainers' perspective.

**Comment by adelbertc** [comment]
Yeah the site is outdated, we haven't pushed a new version yet. The source is up-to-date though: https://github.com/non/cats/blob/master/docs/src/site/index.md

**Comment by fthomas** [comment]
Am I alone in thinking that the Free Monad tut should not contain a Cats version number? Unless we have some automatism that updates the version number prior to a release, it probably will be out of date most of the time.

**Comment by adelbertc** [comment]
Agreed with @fthomas

**Comment by ceedubs** [comment]
@SethTisue thank you for creating this. Getting started should be very straightforward and easy, so issues like this are of great importance. It sounds like your code changes are no longer needed, but I didn't want to close your PR until I was sure we had the meta issues you brought up tracked.

There is #155 for the docs not being automatically published.

I just created #479 for the duplication between the readme and the doc page.

I think those two cover the current issues described in this PR, so I'm going to close it. Feel free to reopen it if you think there's more to it.

Thanks again!

**Pull request closed without merging**
