### PR TITLE
Monoid instance for endomorphic (Co)Kleisli arrow, issue #247

### PR DESCRIPTION
**Pull request by edmundnoble**

### CODE REVIEW

**Comment by non** [comment]
Thanks! You'll need to run `validate` to make sure the style-checks pass.

Look promising. I'll review this later tonight.

**Comment by ceedubs** [comment]
Thanks!

I think these are slightly over-constrained. They require Comonad and Monad when I think only Coflatmap and Flatmap are needed.

**Comment by edmundnoble** [comment]
I believe FlatMap and CoFlatMap introduce Semigroup instances, and `pure` is needed to make it a Monoid. I'll update it accordingly.

Also, is it a good idea to use MonoidK and SemigroupK for this? I tried that earlier, but there was a conflict between (seemingly unrelated) monad instances.

**Comment by ceedubs** [comment]
Oops quite right. I was just thinking of combine.

It seems like SemigroupK and MonoidK could work for this but I'm not sure what error you encountered. Also my track record on this PR isn't great so far ;)

**Comment by edmundnoble** [comment]
I'd really like to add a `Semigroup` instance, but whenever I do it conflicts with the `Monoid` instance because `Monoid` subtypes `Semigroup`, `Monad` subtypes `FlatMap`, and `Comonad` subtypes `CoFlatmap`. I'm not sure what more I can add without implicit resolution falling on its face. 

Style errors fixed.

**Comment by non** [comment]
@edmundnoble The only solution there is to use a series of low priority traits.

```scala
trait Instances0 extends Instances1 {
  // most-specific instances
}

trait Instances1 extends Instances2 {
  // next-most-specific instances which are ambiguous with 0
}

trait Instances2 extends Instances3 {
  // and so on...
}
```

The idea here is that `Monoid` defining methods would be located "before" `Semigroup` defining methods, so they would never be ambiguous. This procedure is tedious, but it works.

**Comment by ceedubs** [comment]
In this particular case, I think that the Monoid instances can probably go into the *Instances classes and the Semigroup instances can go into the *Instances0 classes. I don't think we'll need to create new subtypes for instances like is currently being done.

**Comment by edmundnoble** [comment]
Thank you both, I had no idea about the basis for the *Instances classes before now. I've added Semigroup instances back in as suggested.

**Comment by ceedubs** [comment]
:+1: looks great to me. Thank you!

I'm also interested whether there is anything to be gained by potentially using SemigroupK and MonoidK for these. That could always be explored in a later PR, though.

**Comment by adelbertc** [comment]
Looks good, thank you! :+1:

**Pull request merged**
