### PR TITLE
Add StreamingT tests and fix some uncovered bugs

### PR DESCRIPTION
**Pull request by ceedubs**
And add a couple unit tests for take/drop on StreamingT

### CODE REVIEW

**Comment by stew** [comment]
:+1:

**Comment by ceedubs** [comment]
I've added some more tests and uncovered some more bugs. I'm going to go ahead and add them to this PR.

**Comment by ceedubs** [comment]
Newly fixed bugs:

* isEmpty and nonEmpty were mixed up
* dropWhile was doing takeWhile in the case of Cons

**Comment by ceedubs** [comment]
This PR will bump Cats over the 80% test coverage mark! :sparkles:

**Comment by adelbertc** [comment]
Woot! :+1:

**Comment by stew** [comment]
nice :) :+1:

**Pull request merged**
