### PR TITLE
remove ToStringShow class and refactor Show.fromToString

### PR DESCRIPTION
**Pull request by julien-truffaut**

### CODE REVIEW

**Comment by julien-truffaut** [comment]
@non where they any other reason than performance to introduce `ToStringShow` ?

**Comment by mpilquist** [comment]
:+1:

**Comment by non** [comment]
Honestly I'm not sure what I was thinking. I guess I have a slight preference for named classes, but I support this patch. :+1:

**Comment by non** [comment]
(It looks like there is a scalastyle error? Once Travis passes I'm happy to merge this.)

**Pull request merged**
