### PR TITLE
Add some XorT tests

### PR DESCRIPTION
**Pull request by ceedubs**

### CODE REVIEW

**Comment by non** [comment]
These all look good to me. :+1:

**Comment by ceedubs** [comment]
Codecov.io, aren't you supposed to be giving me a pat on the back?

**Comment by non** [comment]
Huh, yeah, I'll try to look into this at lunch.

**Comment by ceedubs** [comment]
I'm going to go ahead and merge, in accordance with our new rule that PRs that just add tests only need one :+1:.

**Pull request merged**
