### PR TITLE
Disable publishing the aggregate project.

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by travisbrown** [comment]
:+1:, thanks @dwijnand.

**Comment by travisbrown** [comment]
Note that this will need to be manually merged if it goes in after #35.

**Comment by non** [comment]
:+1: great catch

**Comment by non** [comment]
(I just went for it via Github and it seems like it merged correctly.)

**Comment by dwijnand** [comment]
Yeah @travisbrown was just mentioning they'll conflict each other, as can be seen in https://github.com/non/cats/pull/35 is now not auto-mergable.

**Comment by non** [comment]
But isn't it already merged? Maybe I'm confused.

**Comment by dwijnand** [comment]
Not right now:
screen shot 2015-02-02 at 15 30 20

**Comment by travisbrown** [comment]
I'll rebase #35 and we'll be fine—just a second.

**Pull request merged**
