### PR TITLE
Add Apply, Eq/PartialOrder/Order, and Monoid law checking for Const

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by adelbertc** [comment]
Need to make a PR to `algebra` to change the `algebra.laws.OrderLaws#eq` method into something like `eqv` so it can be called (currently conflicts with reference equality).

**Comment by adelbertc** [comment]
All ready now! :-)

**Comment by non** [comment]
:+1: thanks!

**Comment by ceedubs** [comment]
:+1:

**Pull request merged**
