### PR TITLE
remove UpStar and DownStar and add doc for Profunctor

### PR DESCRIPTION
**Pull request by julien-truffaut**
what do you think about using dimap as a single abstract method instead of lmap and rmap?
Anyway if you want an efficient implementation you need to override all of them and if you don't care, you only need to implement one method

### CODE REVIEW

**Comment by ceedubs** [comment]
:+1:

I'm neutral regarding `dimap` vs `lmap` and `rmap`.

**Comment by non** [comment]
@julien-truffaut I agree with your assessment. I'm fine with using `dimap` as the abstract member. :+1: now or if you make that change.

**Comment by julien-truffaut** [comment]
done

**Comment by ceedubs** [comment]
:+1:

**Pull request merged**
