### PR TITLE
Change MonadError from F[_, _] to F[_]

### PR DESCRIPTION
**Pull request by ceedubs**
I was working with MonadError today and the `F[_, _]` approach made me use
quite a few type lambdas when I was working with types like Future/Task.
Since the error type is already encoded as another type parameter, as
far as I know we don't really lose anything by using a type constructor
with a single parameter for `F`.

It's quite possible that there's a reason for using `F[_, _]`. If anyone
knows of one, please speak up.

### CODE REVIEW

**Comment by non** [comment]
I don't have a strong opinion of this change. It seems reasonable to me.

If no one speaks up against it then I would say :+1:

**Comment by ceedubs** [comment]
@adelbertc I think you added `MonadError`. Do you have any thoughts on this? @tpolecat I have heard you chat about error-y type classes like `Catchable`, `MonadError`, etc. Do you have thoughts?

**Comment by adelbertc** [comment]
Hm, this is a lot nicer and no consequences that I can think of at the moment. :+1: from me, though perhaps we should wait to see if @tpolecat has any concerns before merging?

Also should probably do the same for the other ones, `MonadState` and `MonadReader`

**Comment by non** [comment]
@ceedubs assuming @tpolecat does sign-off on this, do you want to follow @adelbertc's suggestion and modify `MonadState` and `MonadReader` also?

**Comment by ceedubs** [comment]
@non @adelbertc sure that looks like it would work. I might not get to this for a couple of days, but I'll give it a go.

**Comment by ceedubs** [comment]
I updated `MonadReader` and `MonadState`.

@adelbertc you mentioned that you were becoming a big fan of these type classes. Do you have a code base using these that you could compile against this branch to see if there might be unfortunate implicit resolution/inference implications? Or are they using Scalaz and not Cats?

**Comment by non** [comment]
If @adelbertc signs off on these then :+1: from me too.

**Comment by adelbertc** [comment]
Looks good to me - the code I have that does use these are all living in Scalaz currently. That being said the tests seem to pick up the instances just fine, so :+1: :-)

**Pull request merged**
