### PR TITLE
Don't infer Null in fromTryCatch

### PR DESCRIPTION
**Pull request by ceedubs**
This is the start of a fix for #591. So far I've only change `Xor`, because I wanted to run this approach by people. If people like this approach, then I can also update `Validated` and try to add some more tests to this PR.

I also renamed `fromTryCatch` to `catching`, because it's a bit less verbose and I like the sound of it a little more. I can change it back if people would prefer though.

### CODE REVIEW

**Comment by ceedubs** [comment]
By the way, this is what happens now if you omit the type parameter on `catching`:

```
scala> Xor.catching(throw new RuntimeException("blargh"))
<console>:14: error: ambiguous implicit values:
 both method ambiguousNull1 in object NotNull of type => cats.NotNull[Null]
 and method ambiguousNull2 in object NotNull of type => cats.NotNull[Null]
 match expected type cats.NotNull[Null]
       Xor.catching(throw new RuntimeException("blargh"))
```

**Comment by ceedubs** [comment]
Looking at that error message, I'm a bit tempted to hack around the fact that you can't do something like `implicitNotFound` for ambiguous implicit values and encode a helpful message in the function names instead of just using `ambigrousNull1` and `ambiguousNull2` :)

**Comment by non** [comment]
Using descriptive method names there sounds smart.

**Comment by non** [comment]
Also, I feel like we talked about this before, but how would you feel about a simpler variation that was something like this:

```scala
def catching(body: => A): Xor[Throwable, A] =
  try { Right(body) } catch { case e: NonFatal => Left(e) }
```

Often when working with exceptions I don't care about the type, and the syntax is a lot nicer if you can leave off the annotations.

**Comment by refried** [comment]
@ceedubs: you’ve probably seen this, but:

```
implicitAmbiguous annotation

The @implicitAmbiguous annotation allows customizing the error message when an implicit search finds multiple ambiguous values. Refer to the Scaladoc of the annotation class for an example.

Thanks to @puffnfresh for this contribution!
```
in scala 2.12.0-M3

**Comment by ceedubs** [comment]
@refried @puffnfresh I didn't know about `@implicitAmbiguous`. That's wonderful!

@non is you preference for `catchAll` because just because it's more concise than `catchingNonFatal`? I would lean toward being consistent with `catching` vs `catch`, and I have a slight leaning toward `NonFatal` as more descriptive than `All`, but I don't have particularly strong feelings about this, so I'm fine with changing it.

**Comment by ceedubs** [comment]
I've updated my PR. What do people think?

Specifically @non and @mpilquist, since both of you discussed this with me.

Also big thanks to @tpolecat because tut caught several places where I had neglected to update the documentation after these changes :)

**Comment by non** [comment]
This seems fine to me. :+1: 

(I think I'd prefer `catchAll` but I can live with `catchNonFatal` -- it reads pretty well in an imperative way: "catch non-fatal exceptions")

**Comment by ceedubs** [comment]
@non for what it's worth, [this](https://gitter.im/non/cats?at=5638b4a4a530033014e3ce6a) is the conversation that led me to stick with `catchNonFatal` instead of `catchAll`. If you feel strongly about this, I'm fine with changing it though.

**Pull request merged**
