### PR TITLE
Add some Free/Coyoneda instances/helpers

### PR DESCRIPTION
**Pull request by ceedubs**

### CODE REVIEW

**Comment by ceedubs** [comment]
Actually `Functor.map` is strict in Cats, so I don't think there's any use in making the argument by-name in `liftF` and `liftFC`. I'll go ahead and change that on this PR as well.

**Comment by non** [comment]
Hey this is a totally style robot concern, but would you be willing to rewrite comments like:

```scala
/** Interpret a free monad over a free functor of `S` via natural transformation to monad `M`. */
```

as:

```scala
/**
 * Interpret a free monad over a free functor of `S` via natural transformation to monad `M`.
 */
```

?

**Comment by non** [comment]
(I would be tempted to wrap the line as well -- you can see that it is long enough that it doesn't fit in a github comment.)

**Comment by ceedubs** [comment]
@non is this good?

**Comment by non** [comment]
Perfect thanks! :+1:

**Pull request merged**
