### PR TITLE
Add tests to cover derived methods leftMap and rightMap on BiFunctor

### PR DESCRIPTION
**Pull request by mikejcurry**
This PR would add tests that should cover identity for the derived leftMap and rightMap on BiFunctor.

I guess this PR is exploratory:
* Is this a suitable use of the laws infrastructure? Seems to be a good use, but not sure if you would actually consider them laws.

Also:
* There is no syntax for leftMap and rightMap at this stage, just bimap; would it make sense to add these as syntax also. I’ve not done that in this PR, but if it is generally in line with what we want to do I can add.

### CODE REVIEW

**Comment by ceedubs** [comment]
:+1: thanks!

> Is this a suitable use of the laws infrastructure?

At some point #370 may provide some answers to this. However, until we have something better in place, I think these sorts of checks are good. There is also a precedent [here](https://github.com/non/cats/pull/562#issuecomment-146380855).

> There is no syntax for leftMap and rightMap at this stage, just bimap; would it make sense to add these as syntax also.

Yes, I think so. We would inherit them for free if Simulacrum supported type classes for type constructors of kind `F[_, _]`. Since it doesn't, it would probably be handy to add them manually.

**Comment by mikejcurry** [comment]
@ceedubs - Cool, Thanks. I've gone ahead and locally made changes to add leftMap and rightMap to syntax, added associativity checks for leftMap and rightMap, and updated the tests to use the syntax additions. Would you folks prefer pushing to this PR or a separate PR after this one?

**Comment by ceedubs** [comment]
@mikejcurry I have no real preference. I have no objections to you adding those changes to this PR. The more changes you add to a PR the more likely one of them will raise objections, but these seem pretty uncontroversial to me :)

**Comment by mikejcurry** [comment]
@ceedubs Sounds good - I'll push the changes to this PR and keep the set of changes in the same area together.

**Comment by ceedubs** [comment]
:+1:

**Comment by non** [comment]
:+1:

**Pull request merged**
