### PR TITLE
Add XorT.orElse

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by rossabaker** [comment]
The second test is so we don't repeat scalaz/scalaz#1037.

**Comment by stew** [comment]
:+1:

**Comment by adelbertc** [comment]
:+1:

**Comment by ceedubs** [comment]
I don't think AA needs to be a subtype of A.

**Comment by ceedubs** [comment]
I don't think As needs to be a supertype of A.

**Pull request merged**
