### PR TITLE
Bumped simulacrum to 0.5.0.

### PR DESCRIPTION
**Pull request by milessabin**

### CODE REVIEW

**Comment by ceedubs** [comment]
Looks like the 2.10 build failed :(

```
[error] /home/travis/build/non/cats/laws/src/main/scala/cats/laws/SerializableLaws.scala:31: exception during macro expansion: 
[error] java.lang.AbstractMethodError: bricks.PlatformMacros.macrocompat$MacroCompat$_setter_$TERMmode_$eq(I)V
[error] 	at macrocompat.MacroCompat$class.$init$(macrocompat.scala:76)
[error] 	at bricks.PlatformMacros.<init>(Platform_jvm.scala:11)
[error] 	at bricks.PlatformMacros$.isJsImpl(Platform_jvm.scala:11)
[error]     if (Platform.isJs) Prop(_ => Result(status = Proof)) else Prop { _ =>
[error]                  ^
[error] one error found
```

**Comment by milessabin** [comment]
Ouch ... I'll investigate.

**Comment by milessabin** [comment]
OK, the problem appears that the laws project is using,
```
"com.github.inthenow" %%% "bricks-platform" % "0.0.1"
```
Which is a defunct precursor to [catalysts](https://github.com/InTheNow/catalysts) and which uses a very old (1.0.0!) and binary incompatible version of macro-compat. The fix would be to migrate to the latest version of catalysts.

Tagging @InTheNow ...

**Comment by InTheNow** [comment]
Checking now.... apologies for the delay ;)

**Comment by InTheNow** [comment]
Yes, `git diff` below, As @milessabin pointed out 

```diff
diff --git a/build.sbt b/build.sbt
index c323877..f4f738f 100644
--- a/build.sbt
+++ b/build.sbt
@@ -26,7 +26,7 @@ lazy val commonSettings = Seq(
     Resolver.sonatypeRepo("snapshots")
   ),
   libraryDependencies ++= Seq(
-    "com.github.mpilquist" %%% "simulacrum" % "0.4.0",
+    "com.github.mpilquist" %%% "simulacrum" % "0.5.0",
     "org.spire-math" %%% "algebra" % "0.3.1",
     "org.spire-math" %%% "algebra-std" % "0.3.1",
     "org.typelevel" %%% "machinist" % "0.4.1",
@@ -135,7 +135,7 @@ lazy val laws = crossProject.crossType(CrossType.Pure)
   .settings(disciplineDependencies:_*)
   .settings(libraryDependencies ++= Seq(
     "org.spire-math" %%% "algebra-laws" % "0.3.1",
-    "com.github.inthenow" %%% "bricks-platform" % "0.0.1"))
+    "org.typelevel" %%% "catalysts-platform" % "0.0.2"))
   .jsSettings(commonJsSettings:_*)
   .jvmSettings(commonJvmSettings:_*)
 
@@ -170,7 +170,7 @@ lazy val tests = crossProject.crossType(CrossType.Pure)
   .settings(noPublishSettings:_*)
   .settings(libraryDependencies ++= Seq(
     "org.scalatest" %%% "scalatest" % "3.0.0-M7" % "test",
-    "com.github.inthenow" %%% "bricks-platform" % "0.0.1" % "test"))
+    "org.typelevel" %%% "catalysts-platform" % "0.0.2" % "test"))
   .jsSettings(commonJsSettings:_*)
   .jvmSettings(commonJvmSettings:_*)
 
diff --git a/laws/src/main/scala/cats/laws/SerializableLaws.scala b/laws/src/main/scala/cats/laws/SerializableLaws.scala
index eb532f1..825dc40 100644
--- a/laws/src/main/scala/cats/laws/SerializableLaws.scala
+++ b/laws/src/main/scala/cats/laws/SerializableLaws.scala
@@ -4,7 +4,7 @@ package laws
 import org.scalacheck.Prop
 import org.scalacheck.Prop.{ False, Proof, Result }
 
-import bricks.Platform
+import catalysts.Platform
 
 /**
  * Check for Java Serializability.
diff --git a/tests/src/test/scala/cats/tests/CatsSuite.scala b/tests/src/test/scala/cats/tests/CatsSuite.scala
index 4b7b48f..8594d86 100644
--- a/tests/src/test/scala/cats/tests/CatsSuite.scala
+++ b/tests/src/test/scala/cats/tests/CatsSuite.scala
@@ -1,7 +1,7 @@
 package cats
 package tests
 
-import bricks.Platform
+import catalysts.Platform
 
 import cats.std.AllInstances
 import cats.syntax.{AllSyntax, EqOps}

```

**Comment by milessabin** [comment]
What is that diff against? Is it another PR that's pending?

**Comment by InTheNow** [comment]
It's a diff against master - i.e. what your PR should have in it

**Comment by milessabin** [comment]
I don't see that change on master ... is there some other PR pending?

**Comment by milessabin** [comment]
Or are you asking me to retype that diff?

**Comment by ceedubs** [comment]
Retyping shouldn't be necessary, as `git apply` can take a diff file as an argument. I'll submit a PR with the proposed changes.

**Comment by ceedubs** [comment]
I just submitted #643. Here's to hoping that the build passes...

**Comment by ceedubs** [comment]
Looks like @InTheNow's changes passed the build over on #643. I'm going to close this out in favor of that one.

**Pull request closed without merging**
