### PR TITLE
Add syntax for validated.

### PR DESCRIPTION
**Pull request by coltfred**
Add syntax to values for lifting them into `Valid`, `Invalid` and the Nel versions of those. Currently no tests as I was unable to figure out which mechanism was preferred for testing syntax.

Let me know how that should be done.

Addresses #585.

### CODE REVIEW

**Comment by ceedubs** [comment]
:+1:

I would vote for merging this and creating a separate issue for testing syntax. And possibly another one for whether we should be using `Eval` instead of by-name params for these?

**Comment by ceedubs** [comment]
By the way, thanks @coltfred!

**Comment by julien-truffaut** [comment]
:+1: I agree with @ceedubs we should discuss `Eval` and test in a separate issue

**Comment by coltfred** [comment]
No problem!

**Pull request merged**
