### PR TITLE
Update to kind projector 0.5.4

### PR DESCRIPTION
**Pull request by ceedubs**

### CODE REVIEW

**Comment by dwijnand** [comment]
Just out out of interest, what does 0.5.4 bring?

**Comment by ceedubs** [comment]
It fixes an issue where kind-projector was [creating trees with no position](https://github.com/non/kind-projector/issues/7).

It also supports parameterized placeholders in inline syntax:

```scala
XorT[?[_], Int, ?]    // equivalent to: type R[F[_], B] = XorT[F, Int, B]
```

**Comment by dwijnand** [comment]
I see. Thanks Cody.

**Comment by stew** [comment]
:+1:

**Pull request merged**
