### PR TITLE
Issue/197 - Free docs+enhancements - First part

### PR DESCRIPTION
**Pull request by mandubian**

### CODE REVIEW

**Comment by ceedubs** [comment]
@mandubian thanks for all of the work you have done on this.

I can't speak for others, but my thought is this:
In the interest of moving things along and not burning you out too much on documentation, maybe you could add tests for FreeApplicative (probably making sure that it satisfies the applicative laws is enough) and merge in master so this can be merged. Then maybe we can merge this and people can step in to help with the docs?

Does that sound all right to people?

**Comment by mandubian** [comment]
I'll add some tests for FreeApp!

**Comment by non** [comment]
This looks great! :+1: 

I think there is still some clean up that the docs could use, but given the renaming and project changes I'd rather merge this PR first and then allow many different folks to contribute to the clean up effort.

**Comment by mandubian** [comment]
I agree about the doc... I cleaned it a bit but as I moved some parts, it might be good to clean it a bit...
anyway, I agree that it would be better to merge it and go on later ;)

**Comment by fthomas** [comment]
:+1:

**Pull request merged**
