### PR TITLE
ifM and mproduct combinators

### PR DESCRIPTION
**Pull request by wedens**

### CODE REVIEW

**Comment by refried** [comment]
Is this one of those places where we're supposed to use Lazy instead of `=> A`, and if so, is the benefit worth the syntactic penalty?

**Comment by wedens** [comment]
@refried good question

**Comment by non** [comment]
I think the answer to that question boils down to which you want more:

 * lightweight syntax (if so, go with `=> F[B]`)
 * better performance (if so, go with `Lazy[F[B]]`)

The reason I say that performance is better for `Lazy[_]` is that you give the caller more control of how the arguments are evaluated. `=> F[B]` will allocate a thunk (i.e. `Function0`) every time you use it. However, users can opt to use `Lazy.eager(fb)` if they don't need short-circuiting behavior (or if they already have an `F[B]` value in-hand). Similarly, if the value is very cheap to create, you may not want to bother memoizing it (as you are doing with `lazy val`). Using `Lazy.byName(...)` provides the laziness but not the memoization.

If you were calling `ifM` millions of times having these options could make a difference. That said, I would be fine with using by-name parameters here. Just wanted to be clear about what possible benefit you could get from using `Lazy[_]` here.

**Comment by wedens** [comment]
@non yeah, right. I don't think somebody will call ifM millions of times :)

**Comment by refried** [comment]
Wait, why wouldn't they call `ifM` millions of times?  i.e. use `ifM` in a hot-spot?

This is the first `=> A` outside of `Lazy` and `Free`.  If folks really want to do the `Lazy` experiment, isn't this is where to start?

P.S.  if we're assuming no side effects, `Lazy.byName(...)` is never desirable over `Lazy.eager(fb)`, right?

**Comment by wedens** [comment]
I think something about when Lazy shoud be used instead of call by name should be in contributor guide.

**Comment by refried** [comment]
@wedens *nod*

**Comment by ceedubs** [comment]
:+1: this looks good to me.

**Pull request merged**
