### PR TITLE
Move BigInt and BigDecimal to their own files

### PR DESCRIPTION
**Pull request by amir**
Addressing #118

I obviously have no idea what I'm doing. I read @stew's blog post and found #118 being both `low-hanging fruit` and `ready`.  Made the changes that I deemed necessary. Apologies in advance if merging/reviewing it is more trouble than it's worth—FWIW `sbt validate` didn't complain.

### CODE REVIEW

**Comment by non** [comment]
It's a small thing, but can you rename `bigint.scala` to be `bigInt.scala` so it matches the `object bigInt` definition? I'm not sure if other folks like this convention but I think we should try to be consistent here.

**Comment by amir** [comment]
Renamed both files.

**Comment by ceedubs** [comment]
:+1:

**Comment by stew** [comment]
:+1:

**Pull request merged**
