### PR TITLE
Enforce binary compatibility with MiMa SBT plugin

### PR DESCRIPTION
**Pull request by DavidGregory084**
~~This should not be merged until 0.4.0 is released with cats-kernel as a distinct artifact.~~

Enables the Migration Manager SBT plugin for the kernel module and ensures binary compatibility issues are reported by `validateJVM`.

### CODE REVIEW

**Comment by DavidGregory084** [comment]
Specific breaking changes can be allowed as per Migration Manager's docs: [Sbt plugin: Advanced Usage (Filtering Binary Incompatibilities)](https://github.com/typesafehub/migration-manager/wiki/Sbt-plugin#advanced-usage-filtering-binary-incompatibilities)

**Comment by dwijnand** [comment]
:+1: for putting this in place now

In your place I would:
* set `previousArtifacts` to an empty set
* open a ticket about adding cats-kernel 0.4.0 to it post-0.4.0 release
* leaving a comment next to that empty `previousArtifacts` explaining it's in place for cats-kernel's first release with the ticket number
* getting this merged into master today :)

**Comment by DavidGregory084** [comment]
Will do, thanks @dwijnand :)

**Comment by non** [comment]
:+1:

**Comment by non** [comment]
Thanks!

**Comment by dwijnand** [comment]
:+1:

**Comment by ceedubs** [comment]
Fantastic. Thanks @DavidGregory084! I tried this once before and couldn't get it figured out. You have succeeded where I failed :)

**Comment by dwijnand** [comment]
Oh this was pull requested to topic/kernel, not master.

**Comment by DavidGregory084** [comment]
@dwijnand Yep, and it only checks kernel right now - I think this could be expanded pretty easily after 1.0 though!

**Pull request merged**
