### PR TITLE
add setMonoid

### PR DESCRIPTION
**Pull request by drostron**
[gitter discussion](https://gitter.im/non/cats?at=55e23450fbbdfcbd3b5de06f)

### CODE REVIEW

**Comment by non** [comment]
:+1: Thanks!

**Comment by ceedubs** [comment]
It will probably require adding a questionable `Eq` instance for sets, but could we test this against the monoid laws?

**Comment by drostron** [comment]
Sure. I need to familiarize with law checking a bit more first (been itching to do so for awhile so this is a welcomed opportunity). The next few days are filled, but should have some time after that.

**Comment by drostron** [comment]
Pushed a commit adding law checking for `setMonoidInstance`. @ceedubs, I'm curious if this PR introduces a questionable `Eq` instance for sets. If so I'm interested to learn more.

**Comment by ceedubs** [comment]
:+1: looks good to me.

I was surprised to see that `Eq` instance for sets was in scope. It looks like algebra has provided one for quite a while (not introduced with this PR). I suppose it makes sense to have it if you are working with `Set`, since it's based on universal equality anyway.

**Comment by ceedubs** [comment]
The only thing added since @non gave a :+1: is law-checking which I can't imagine he would be opposed to :). I'm going to merge this. Thanks!

**Pull request merged**
