### PR TITLE
Revise Fold to be its own trampoline.

### PR DESCRIPTION
**Pull request by non**
This commit explores Miles' suggestion that allowing users
to use the andThen and compose methods to build Fold instances
in a stack-safe way makes the type more approachable.

This also simplifies the partialIterate method a bit.

(Don't merge this yet -- if we agree this is the right direction
then I need to update some documentation first.)

### CODE REVIEW

**Comment by ceedubs** [comment]
It looks like in both the case of `compose` and `andThen` we are using `List` concatenation. Is this a performance concern?

**Comment by non** [comment]
@ceedubs So, in most expected cases the expectation is that the LHS of `andThen` will be quite small (either 0 or 1 elements in the case of `Pass` and `Continue` respectively). I think in the current cases this will be totally fine.

The impetus behind this change was that Miles noticed that to use `Fold` correctly users had to set up their own pseudo-trampoline (as `partialIterate` did). The goal here was to allow folds to compose in a safe way.

**Comment by ceedubs** [comment]
@non that makes sense. Thanks for the explanation. :+1:.

**Comment by milessabin** [comment]
Also, difference between the footprints of a list of functions and a composed function is minimal ... the new function value that's constructed by `f compse g` is, to all intents and purposes, a hidden cons node.

:+1: from me ... thanks :-)

**Comment by ceedubs** [comment]
@non is this good to merge now, or did you still have some documentation you wanted to change?

**Comment by non** [comment]
Oh, yes, I do want to update the `Fold` docs. I'll do that today and then merge this.

**Comment by ceedubs** [comment]
This will need a rebase once you have a chance to update the docs.

**Comment by non** [comment]
This commit is superseded by #418.

**Pull request closed without merging**
