### PR TITLE
Restore ScalaDoc generation for most types

### PR DESCRIPTION
**Pull request by mpilquist**
Upgrades simulacrum and paradise.

### CODE REVIEW

**Comment by non** [comment]
:+1:

**Comment by travisbrown** [comment]
Instead of disabling ScalaDoc for comments that refer to `Validation`, do you think there'd be too much overhead involved in pulling all references to types that don't exist yet and creating a new issue to track the need to document this relationship once they're introduced?

**Comment by non** [comment]
@travisbrown Yeah actually that does seem like a better approach. What do you think @mpilquist ?

**Comment by mpilquist** [comment]
:+1:

**Comment by travisbrown** [comment]
:+1:

**Pull request merged**
