### PR TITLE
Move cats-free and cats-state in to cats-core

### PR DESCRIPTION
**Pull request by DavidGregory084**
To address #760

### CODE REVIEW

**Comment by mpilquist** [comment]
:+1:

**Comment by milessabin** [comment]
:+1:

**Comment by mikejcurry** [comment]
Minor, but I had added the following text to the contributors guide a short time ago: *"Tests for additional modules, such as free, go into the tests directory within that module."*

If this goes through, and free moves into core, then it might make sense to change the above text to refer to the jvm module instead of referring to free, as free will no longer be a separate module and the tests have been factored to the main tests directory. I can push through a separate change at some stage if it doesn't make this one, but for consistency it might be better to change the docs and the code together.

**Comment by DavidGregory084** [comment]
Thanks for pointing that out; not near a PC at the minute but I'll try and address the documentation changes this evening.

**Comment by non** [comment]
Rerunning tests now. :+1: once they pass.

**Comment by non** [comment]
Thanks!

**Pull request merged**
