### PR TITLE
Topic/syntax

### PR DESCRIPTION
**Pull request by non**
Here's a first pass at setting up syntax in cats.

High-level stuff:

1. Syntax lives in `core`
2. Syntax contained in the "most general" class
3. Specific imports work, e.g. `import cats.syntax.functor._`
4. General import works, e.g. `import cats.syntax.all._`
5. Omnibus import for syntax + instances works, e.g. `import cats.implicits._`

Let me know what you think!

### CODE REVIEW

**Comment by stew** [comment]
:+1: LGTM 

out of curiosity, why curry imap?

**Comment by julien-truffaut** [comment]
I suppose to make it consistent with `dimap`?

**Comment by ceedubs** [comment]
If we were to move the implicit evidence requirements from the Ops constructors to the methods I think we could have the Ops classes extend AnyVal and avoid allocations for syntax. Is this something we would get for free once we are using simulacrum for this?

There would also be downsides. One is verbosity. Another is that if IDE users do an omnibus import, suddenly every type class method in cats starts showing up in the auto-complete for every single object.

**Comment by non** [comment]
So I did find it more consistent to have each function passed independently.

I also found that without a curried `imap` you always have to annotate the function arguments, since you have no idea what `B` will be. If you provide `A => B` first, then inference works.

As far as using value classes -- my plan is actually to use Machinist eventually. I could do that in this PR or just get the syntax in first and then do it. My experience is that value classes for operators are OK but not as efficient as eliminating the ops classes entirely with macros.

**Comment by non** [comment]
(Also there are a few classes I forgot to add, so I'll push those now.)

**Comment by non** [comment]
Alright, at this point I think this should be good to merge if folks agree.

**Comment by non** [comment]
(I will set up Machinist macros in another branch.)

**Comment by ceedubs** [comment]
:+1: and #78 created to track machinist feature

**Pull request merged**
